In [63]:
### Numpy is Numeric Py
import numpy as np
list1 = ['Artificial Intelligence',1,2,3,10]
print(list1)
print(type(list1))
np.array(list1)
type(np.array(list1))

print(np.array([1,2,3,4,5.]))

print(np.array([1,2,3,4,5.]).ndim)
print(np.array([[1,2,3],[4,5,6]]))


['Artificial Intelligence', 1, 2, 3, 10]
<class 'list'>
[1. 2. 3. 4. 5.]
1
[[1 2 3]
 [4 5 6]]


In [29]:
## dimension of the numpy array
np.array([[1,2,3],[4,5,6]]).ndim


2

In [51]:

## assignt he numpy to variable

variable = np.array([[1,2,3],[4,5,6]])
variable[0][1]

2

In [52]:
## assignt he numpy to variable

variable = np.array([[1,2,3],[4,5,6]])
variable[0][1]

2

In [53]:
## How to make the single to multiple dimensions
np.array([1,2,3,4,5], dtype='float',ndmin= 3)

##provide the (configuration, Rows, Column)




array([[[1., 2., 3., 4., 5.]]])

In [54]:

## Get  the shape of the numpy array
np.array([1,2,3,4,5,6,7,8,9], dtype='float',ndmin= 2).shape

(1, 9)

In [21]:
## Get  the shape of the numpy array
np.array([1,2,3,4,5], dtype='float',ndmin= 3).shape

(1, 1, 5)

In [24]:
## Get  the shape of the numpy array
np.array([[[1,2,3,4,5],[4,5,6,7,8],[8,9,10,11,12]],[[1,2,3,4,5],[4,5,6,7,8],[8,9,10,11,12]]], dtype='float').shape

(2, 3, 5)

In [28]:
## Get  the shape of the numpy array
np.array(
    [
        [
            [
                [1,2,3,4,5],[4,5,6,7,8],[8,9,10,11,12]
            ],
            [
                    [1,2,3,4,5],[4,5,6,7,8],[8,9,10,11,12]
            ]
        ], 
        [
            [
                [1,2,3,4,5],[4,5,6,7,8],[8,9,10,11,12]
            ],
            [
                [1,2,3,4,5],[4,5,6,7,8],[8,9,10,11,12]
            ]
        ]
    ], dtype='float').shape

(2, 2, 3, 5)

In [31]:
## np as array
np.array([1,2,3,4,5,6])


array([1, 2, 3, 4, 5, 6])

In [56]:
## np as matrix
np.mat([1,2,3,4,5])

np.mat([1,2,3,4,5]).ndim

2

In [57]:
list1 = [1,2,3,4,5,6,7]


In [58]:
## anyarray conert in array
np.asarray(list1)

array([1, 2, 3, 4, 5, 6, 7])

In [59]:
## asanyarray Covert in array
np.asanyarray(np.asarray(np.array(list1)))

array([1, 2, 3, 4, 5, 6, 7])

In [42]:
## asanyarray Covert in array
np.asanyarray(np.asarray(np.mat(list1)))

array([[1, 2, 3, 4, 5, 6, 7]])

In [37]:
np.mat(list1)

matrix([[1, 2, 3, 4, 5, 6, 7]])

In [38]:
np.asanyarray(list1)

array([1, 2, 3, 4, 5, 6, 7])

In [60]:
np.asanyarray(np.mat(list1))


matrix([[1, 2, 3, 4, 5, 6, 7]])

###Create an array from function 

In [44]:
###Create array from function
np.fromfunction(lambda i,j : i*j, (4,4),dtype= int)

array([[0, 0, 0, 0],
       [0, 1, 2, 3],
       [0, 2, 4, 6],
       [0, 3, 6, 9]])

In [64]:
###Create array from function
np.fromfunction(lambda i,j : i*j, (2,4),dtype= int)

array([[0, 0, 0, 0],
       [0, 1, 2, 3]])

In [46]:
###Create array from function
np.fromfunction(lambda i,j,k: i*j*k, (4,4,4),dtype= int)


array([[[ 0,  0,  0,  0],
        [ 0,  0,  0,  0],
        [ 0,  0,  0,  0],
        [ 0,  0,  0,  0]],

       [[ 0,  0,  0,  0],
        [ 0,  1,  2,  3],
        [ 0,  2,  4,  6],
        [ 0,  3,  6,  9]],

       [[ 0,  0,  0,  0],
        [ 0,  2,  4,  6],
        [ 0,  4,  8, 12],
        [ 0,  6, 12, 18]],

       [[ 0,  0,  0,  0],
        [ 0,  3,  6,  9],
        [ 0,  6, 12, 18],
        [ 0,  9, 18, 27]]])

In [47]:
###Create array from function
np.fromfunction(lambda i,j: i==j, (4,4),dtype= int)

array([[ True, False, False, False],
       [False,  True, False, False],
       [False, False,  True, False],
       [False, False, False,  True]])

## Convert array into Dataframe using Pandas

In [48]:
import pandas as pd
a = np.fromfunction(lambda i,j: i*j, (400,100),dtype= int)
pd.DataFrame(a)

0    1    2     3     4     5     6     7     8     9   ...     90  \
0     0    0    0     0     0     0     0     0     0     0  ...      0   
1     0    1    2     3     4     5     6     7     8     9  ...     90   
2     0    2    4     6     8    10    12    14    16    18  ...    180   
3     0    3    6     9    12    15    18    21    24    27  ...    270   
4     0    4    8    12    16    20    24    28    32    36  ...    360   
..   ..  ...  ...   ...   ...   ...   ...   ...   ...   ...  ...    ...   
395   0  395  790  1185  1580  1975  2370  2765  3160  3555  ...  35550   
396   0  396  792  1188  1584  1980  2376  2772  3168  3564  ...  35640   
397   0  397  794  1191  1588  1985  2382  2779  3176  3573  ...  35730   
398   0  398  796  1194  1592  1990  2388  2786  3184  3582  ...  35820   
399   0  399  798  1197  1596  1995  2394  2793  3192  3591  ...  35910   

        91     92     93     94     95     96     97     98     99  
0        0      0      0      0      0      0      0      0      0  
1       91     92     93     94     95     96     97     98     99  
2      182    184    186    188    190    192    194    196    198  
3      273    276    279    282    285    288    291    294    297  
4      364    368    372    376    380    384    388    392    396  
..     ...    ...    ...    ...    ...    ...    ...    ...    ...  
395  35945  36340  36735  37130  37525  37920  38315  38710  39105  
396  36036  36432  36828  37224  37620  38016  38412  38808  39204  
397  36127  36524  36921  37318  37715  38112  38509  38906  39303  
398  36218  36616  37014  37412  37810  38208  38606  39004  39402  
399  36309  36708  37107  37506  37905  38304  38703  39102  39501  

[400 rows x 100 columns]