In [ ]:
## different functions used in numpy array
import numpy as np
list1 = [1,2,3,4,5,6,7,8,9,10,11,12]
arr = np.asarray(list1)
print(arr)
print (type(arr))
print (arr.shape)
print(arr.ndim)

### Reshape the array
arr1 = arr.reshape(2,3,2)
print(arr1)
print (arr1.shape)
print(arr1.ndim)


In [ ]:
import numpy as np

list3 = [1,2,3,4,5,6,5,4,3,2,1]

newArr1 = np.array(list3, ndmin=1, dtype= float)
print("array:",newArr1)
print("Dimension:",newArr1.ndim)
print("Shape:",newArr1.shape)
newArr2 = np.array(list3, ndmin=2, dtype= int)
print("Array2:",newArr2)
newArr3 = np.array(list3, ndmin=3, dtype= int)
print("Array3:",newArr3)

newArr = np.array([[1,2,3,4],[5,6,7,8]])
print("Array define with array function: ",newArr)
print("Vale of [1][3]:",newArr[1][3])

## Convert in to array
list1 = [2,3,4,5,False]
newArr1 = np.asarray(np.array(list1))
print(newArr1)

mat = np.matrix(list1)
print("Matrix",mat)
print(mat.ndim)

arrNew = np.asarray(mat)
print("New Array",arrNew)

arrNew2 = np.asanyarray(np.array(list3))
print("ArrayNew2:",arrNew2)


In [ ]:
##Copy the array
print("Original Array:", arr)
arrayCopy = arr.copy()
print("Copy array :",arrayCopy)
arrayCopy [1] = 30
print("After Change [1] element:",arrayCopy)
print("Original Array:", arr)

In [ ]:
# program to define arrray with dimensions and type, View of array, change in view will change the original array as well
listTest = [1,2,3,4,5,6,7,8,9]
arrTest = np.array(listTest, ndmin=3, dtype = 'i4')
print(" Original array element:", arrTest)
print(type(arrTest))
arrTest1 = arrTest.view()
print(" Array View :", arrTest1)
arrTest1[0][0][0]= 10
print(" After change in view the Original array element:", arrTest)




In [ ]:
## Shaping and Reshaping an array
print("Original Array:",arrTest)
print("dimension of array:", arrTest.ndim)
print("shape of array:", arrTest.shape)
print("After Reshaping :",arrTest.reshape(9,1))

In [ ]:
#create matrix, create array from matrix and create array from array

matrixTest1 = np.mat((1,2,3,4),dtype='str')
print("new Matrix matrixTest1:", matrixTest1)

matrixTest = np.asmatrix(matrixTest1,dtype='int')
print("Matrix using asmatrix function:", matrixTest)

print("using asarray",np.asarray(matrixTest, dtype= 'float'))
print("using asanyarray function",np.asanyarray(np.asarray(matrixTest, dtype= 'float'),dtype='str'))



In [ ]:
## Creating an array from fucntion (using lambda)

arrFunction = np.fromfunction(lambda i,j : i*j, (3,3),dtype='int')
print("Created array0 using lambda function: \n",arrFunction)


arrFunction1 = np.fromfunction(lambda i,j : i+j, (3,3),dtype='int')
print("Created array1 using lambda function: \n",arrFunction1)


arrFunction2 = np.fromfunction(lambda i,j : i==j, (3,3),dtype='float')
print("Created array2 using lambda function: \n",arrFunction2)


arrFunction3 = np.fromfunction(lambda i,j : i**2, (3,3),dtype='int')
print("Created array3 using lambda function: \n",arrFunction3)


arrFunction4 = np.fromfunction(lambda i,j,k : i*j*k , (4,4,4),dtype='int')
# print("Created array4 using lambda function: \n",arrFunction4)

for x in arrFunction4 :
    print("\n iterative",x)

###Convert array into Dataframe using Pandas

In [ ]:
## Convert array into Dataframe using Pandas

import pandas as pd
a = np.fromfunction(lambda i,j : i*j, (100,400), dtype= 'int')
pd.DataFrame(a)

In [ ]:
### Iterative using for

arrValue = np.fromfunction(lambda i,j : i*j,(3,3), dtype= 'int')
print(arrValue)


for x in arrValue:
    print("Row wise value of array",x)


for x in arrValue:
    for y in x:
        print("element wise value :",y)


for i in np.nditer(arrValue):
    print("printing value using nditer function rather then multiple loops", i)


## Iterating array sing different datatype
for i in np.nditer(arrValue,flags=['buffered'],op_dtypes=['S']):
    print("printing value after converting type using nditer function", i)

In [ ]:
### using nditer and printing value stepwise

print("Original array :\n",arrValue)

for x in np.nditer(arrValue[:, ::2]):
    print("printing the value of array step by 2",x)


In [ ]:
## using ndenumeration

arrOriginal = np.array([[1,2,3,4],[2,3,4,5]])

for idx,i in np.ndenumerate(arrOriginal):
    print("the value at {0} is {1} \n".format(idx,i))

In [ ]:
## Join Arrays using concatenate and stack function
import numpy as np

arr1 = np.array([[1, 2,3], [3, 4,5]])

arr2 = np.array([[5, 6,7], [7, 8,9]])
arr3 = np.array([[50, 60,70], [70, 80,90]])
arrF = np.concatenate((arr1, arr2, arr3), axis=0)
print("Axix 0",arrF)

arr = np.concatenate((arr1, arr2, arr3), axis=1)
print("Axis 1",arr)


## Stack fucntion

import numpy as np

arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.stack((arr1, arr2), axis=1)

print("Stack the array: ",arr)

In [ ]:

# Horizental stack:

import numpy as np

arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.hstack((arr1, arr2))

print("Horizental Stack:",arr)



In [ ]:
## Vertical Stack

import numpy as np

arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.vstack((arr1, arr2))

print("Vertical Stack:",arr)


In [ ]:
#Depth Stack

import numpy as np

arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.dstack((arr1, arr2))

print("Depth Stack:",arr)

In [12]:
### Random array
from numpy import random
var1 = random.rand() ## provide value between 0 and 1
var2 = random.randint(100)
var3 = random.rand(5) # Provide 1 d array of 5 float values
var4 = random.randint(100, size=5) # Provide 1 d array of 5 int values
arr1 = random.rand(2,5) # Provide 2 d array of 2,5  size
arr2 = random.randint(100, size=(2,5)) # Provide 2 d array of 2,5 size 
rnum = random.choice([3, 5, 7, 9]) ## get the random number from arraty
narray = random.choice([3,4,6,7], size=(2,3)) # generate array of size 2,3 using choice of these numbers

probabilityNumber = random.choice([3, 5, 7, 9], p=[0.1, 0.3, 0.6, 0.0], size=(100)) ## 100 values, probability is set by a number between 0 and 1, where 0 means that the value will never occur and 1 means that the value will always occur.
probabilityArray = random.choice([3, 5, 7, 9], p=[0.1, 0.3, 0.6, 0.0], size=(2,3)) ## 100 values, probability is set by a number between 0 and 1, where 0 means that the value will never occur and 1 means that the value will always occur.

print(" Single Random value of floatbetween 0 and 1", var1)
print(" Single Random value of interger", var2)
print(" 1D array of 5 float value", var3)
print(" 1D array of 5 integer value", var4)
print(" 2D array of float values", arr1)
print(" 2D array of integer values", arr2)
print(" get the random number from array", rnum)
print(" generate array of size 2,3 using choice of numbers in 1D array", narray)
print(" Generate 100 Number using probability of values in array", probabilityNumber)
print(" Generate 2 D array using probability of values in array", probabilityArray)




 Single Random value of floatbetween 0 and 1 0.22518362068851994
 Single Random value of interger 42
 1D array of 5 float value [0.63273311 0.28443137 0.50526867 0.46551895 0.67714564]
 1D array of 5 integer value [10  6 57 21 33]
 2D array of float values [[0.27611616 0.18832379 0.37410268 0.28894067 0.28643918]
 [0.69342411 0.23246563 0.70644092 0.2310209  0.22113182]]
 2D array of integer values [[76 84 74 31 13]
 [ 8 18 87 93 79]]
 get the random number from array 7
 generate array of size 2,3 using choice of numbers in 1D array [[7 6 4]
 [7 7 7]]
 Generate 100 Number using probability of values in array [3 7 7 5 5 5 5 7 7 5 5 7 5 5 7 5 7 7 5 7 5 5 7 5 3 7 7 7 7 7 5 7 7 7 7 7 5
 5 7 7 5 5 7 7 7 7 7 7 3 5 5 7 7 3 7 5 5 7 7 7 3 5 7 3 7 7 5 3 5 7 7 7 3 5
 7 5 7 5 7 7 7 5 5 7 7 7 5 5 5 5 5 7 7 7 7 7 7 7 7 7]
 Generate 2 D array using probability of values in array [[7 5 7]
 [7 7 7]]
