Automatic Creation of Array


In [ ]:
import numpy as np

## create array of specific size
print(np.arange(10))


In [ ]:
arr = np.arange(4,10,.5)  ## (start, upto size, step)
arr

In [ ]:
# to comapre and get the specific item from array
arr[arr>8.5]

In [ ]:
arr1 = arr[arr > 8.0]
print(arr1)

In [ ]:
from numpy import random
arr = random.rand(4,5,) ## rand function create array of flaot values
print(arr)


In [ ]:
arr[1,2] ## 2 row and 3 element

In [ ]:
arr[1:3] ## [ start row : upto n-1 row]

In [ ]:
arr[[1,2],3]  ## print [[rows range], column]

In [ ]:
arr [[1,2,3],3] 

In [ ]:
arr[1:3,1] # [row range, column ]

In [ ]:
print(arr)
arr[1:3, 2:4]

In [11]:
L = range(1000)
%timeit [i**2 for i in L]

44.6 µs ± 4.34 µs per loop (mean ± std. dev. of 7 runs, 10,000 loops each)


In [12]:
a = np.arange(1000) # arange is automatic range
%timeit a**2

859 ns ± 96.3 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


In [28]:
a = np.array(1000) # arange is automatic range
%timeit a**2

366 ns ± 29.2 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


In [14]:
a = np.linspace(0,1,50) ## get the 50 element start from 0 to 1
a

array([0.        , 0.02040816, 0.04081633, 0.06122449, 0.08163265,
       0.10204082, 0.12244898, 0.14285714, 0.16326531, 0.18367347,
       0.20408163, 0.2244898 , 0.24489796, 0.26530612, 0.28571429,
       0.30612245, 0.32653061, 0.34693878, 0.36734694, 0.3877551 ,
       0.40816327, 0.42857143, 0.44897959, 0.46938776, 0.48979592,
       0.51020408, 0.53061224, 0.55102041, 0.57142857, 0.59183673,
       0.6122449 , 0.63265306, 0.65306122, 0.67346939, 0.69387755,
       0.71428571, 0.73469388, 0.75510204, 0.7755102 , 0.79591837,
       0.81632653, 0.83673469, 0.85714286, 0.87755102, 0.89795918,
       0.91836735, 0.93877551, 0.95918367, 0.97959184, 1.        ])

In [15]:
arr = np.arange(1,4,2,float) ## (start, end, step, dType)
arr

array([1., 3.])

In [21]:
arr = np.random.randint(1,30)
arr

11

In [17]:
arr = np.random.rand(5,5,2) ##(config,row,column)
arr

array([[[5.11799995e-01, 9.41088039e-01],
        [1.92595777e-01, 2.06702512e-01],
        [6.87631446e-01, 7.14343172e-01],
        [9.19440171e-01, 3.26773572e-02],
        [8.79100465e-01, 2.33955943e-01]],

       [[6.60411743e-01, 5.51419138e-01],
        [4.58288429e-01, 3.45469385e-01],
        [6.19463815e-01, 3.44976648e-01],
        [6.82987350e-01, 4.83480572e-01],
        [3.42230067e-01, 2.70463201e-01]],

       [[7.82137704e-01, 2.76091573e-01],
        [2.66211073e-01, 7.59061007e-01],
        [3.27262589e-01, 8.76361182e-01],
        [9.68377700e-02, 6.33350944e-01],
        [6.84240937e-01, 8.34996301e-01]],

       [[7.74828711e-01, 5.28236377e-01],
        [2.15547054e-01, 3.53069345e-01],
        [5.49073975e-01, 3.99019610e-04],
        [7.80880893e-02, 9.16438260e-01],
        [5.98138339e-01, 7.14699930e-01]],

       [[5.40576912e-01, 4.32157935e-01],
        [7.14933830e-01, 3.99901859e-01],
        [1.03589966e-01, 3.80729589e-01],
        [3.52987282e-01, 6

In [18]:
arr = np.random.randn(2,2,2)
arr

array([[[ 1.13612935,  0.19123135],
        [-0.41214563, -0.93043346]],

       [[-0.03499787,  0.05891298],
        [-0.59889514, -0.22928826]]])

In [19]:
arr = np.random.randn(30)
arr

array([-0.2980319 , -0.07870206, -0.13354835, -0.75598004, -0.61165222,
       -1.93547034, -0.06997787,  0.30416148,  0.85773321,  1.32750719,
       -0.05113248,  0.38491125, -1.35031105,  1.62510066,  1.51570482,
        0.7381102 , -0.63836478,  1.56489974, -0.09148396, -0.43319595,
        0.79499925,  0.02694775, -0.59737786,  0.53233436, -0.81339129,
        1.00407234,  0.5907648 ,  1.56913449,  0.43926099,  0.56049559])

In [20]:
arr = np.random.random(30)
arr

array([0.31096787, 0.7070737 , 0.03234252, 0.96388159, 0.38155137,
       0.32076282, 0.87631319, 0.1040845 , 0.70734177, 0.51215246,
       0.75614939, 0.78647662, 0.10452299, 0.91419137, 0.10726469,
       0.35423737, 0.32376191, 0.60696517, 0.70920996, 0.15102108,
       0.37506273, 0.5743816 , 0.1838579 , 0.02228831, 0.99737711,
       0.48591467, 0.04637572, 0.33526065, 0.13887656, 0.3538931 ])

In [22]:
arr = np.ones((2,2))
arr

array([[1., 1.],
       [1., 1.]])

In [23]:
arr = np.zeros((3,3))
arr

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [24]:
arr = np.eye(4,4,dtype='int')  ## diagonal one
arr

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]])

In [25]:
arr = np.diag((1,2,3,4))
arr

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [29]:
## creating dataframes using list
import pandas as pd 
weatherData = [('1/1/2024', 8,45,'Sunny'),
 ('2/1/2024', 8,45,'Sunny'),
 ('3/1/2024', 8,45,'Sunny'),
 ('4/1/2024', 8,45,'Sunny'),
 ('5/1/2024', 3,45,'Rainy'),
 ('6/1/2024', 45,20,'Hot')
 ]
df =pd.DataFrame(weatherData,columns=('Day', 'Temp','Winspeed','Event'))
df

Day  Temp  Winspeed  Event
0  1/1/2024     8        45  Sunny
1  2/1/2024     8        45  Sunny
2  3/1/2024     8        45  Sunny
3  4/1/2024     8        45  Sunny
4  5/1/2024     3        45  Rainy
5  6/1/2024    45        20    Hot

In [ ]:
pd.DataFrame(np.random.rand(100,2)) ## create dataframe using numpy 

In [26]:
a = np.arange(10)
a[5]


5

In [27]:
a = np.diag([1,2,3])
print(a)
a[2,2]

[[1 0 0]
 [0 2 0]
 [0 0 3]]


3

In [ ]:
a = np.arange(10)  ## slicing the data
print(a)
a[5 :] = 100
print(a)

In [ ]:
a[2:9:2] ## get the element start from 2 up to 9 with step size 2


In [30]:
## change the element of a starting form 5th to range element with b elements // the size of element should be same
a = np.arange(10)
print("a:",a)
b = np.arange(5)
print("b:",b)
a[5:] = b[::-1] ## reverse of element and assign to a
print("after change a :", a)

a: [0 1 2 3 4 5 6 7 8 9]
b: [0 1 2 3 4]
after change a : [0 1 2 3 4 4 3 2 1 0]


In [31]:
a = np.arange(10)
print("a:",a)
print("Address a:",id(a))
b = a[::2]
print("b: ",b)
print("Address b:",id(b))
print(np.shares_memory(a,b))


## One element change will impact other array too
b[1] = 100
print("a:",a)
print("b: ",b)

a: [0 1 2 3 4 5 6 7 8 9]
Address a: 1851103416592
b:  [0 2 4 6 8]
Address b: 1851117809520
True
a: [  0   1 100   3   4   5   6   7   8   9]
b:  [  0 100   4   6   8]


### Operators in numpy array

In [32]:
a = np.array([1,2,3,4])
a+1

array([2, 3, 4, 5])

In [33]:
c = np.diag([1,2,3,4])
c**2

array([[ 1,  0,  0,  0],
       [ 0,  4,  0,  0],
       [ 0,  0,  9,  0],
       [ 0,  0,  0, 16]])

In [34]:
a = np.array([1,2,3,4,5])
b = np.array([5,2,3,2,9])
a==b

array([False,  True,  True, False, False])

In [35]:
a>b


array([False, False, False,  True, False])

In [ ]:
np.array_equal(a,b,)

In [36]:
a  = np.array([1,2,3,4])
b  = np.array([2,3,4,5])
c  = np.array([3,4,5,6])

(a<=b) &(b<=c)

array([ True,  True,  True,  True])

In [37]:
c[3] =1
(a<=b) &(b<=c)

array([ True,  True,  True, False])

In [40]:
x = np.array([1,2,3,4])
y = np.array([[1,2,3], [5,4,7]])
print("x value",x)
print("y value",y)
##The mean is the average of a data set. It can be calculated by adding up all of the numbers in the data set and then dividing by the total number of values in the set.
print(" x mean value : ",x.mean())
print(" y mean Column wise", y.mean(axis= 0)) ## column wise mean
print(" y mean row wise", y.mean(axis= 1)) ## row wise mean


##The median is the middle value (or midpoint) when a data set is ordered from least to greatest.
print(" x Median value : ",np.median(x))
print(" y Median column wise", np.median(y, axis= 0)) ## column wise Median
print(" y Median row wise", np.median(y, axis= 1)) ## row wise Median
print(" y Median value : ",np.median(y))




x value [1 2 3 4]
y value [[1 2 3]
 [5 4 7]]
 x mean value :  2.5
 y mean Column wise [3. 3. 5.]
 y mean row wise [2.         5.33333333]
 x Median value :  2.5
 y Median column wise [3. 3. 5.]
 y Median row wise [2. 5.]
 y Median value :  3.5


In [41]:
## Mode Function
import statistics as st
arr = np.array([1,2,2,3,3,4,5,5,5])
print(" mode value of array is", st.mode(arr))
st.count(3)

 mode value of array is 5


count(3)

In [42]:
data = np.loadtxt('populations.txt')
data

array([[ 1900., 30000.,  4000., 48300.],
       [ 1901., 47200.,  6100., 48200.],
       [ 1902., 70200.,  9800., 41500.],
       [ 1903., 77400., 35200., 38200.],
       [ 1904., 36300., 59400., 40600.],
       [ 1905., 20600., 41700., 39800.],
       [ 1906., 18100., 19000., 38600.],
       [ 1907., 21400., 13000., 42300.],
       [ 1908., 22000.,  8300., 44500.],
       [ 1909., 25400.,  9100., 42100.],
       [ 1910., 27100.,  7400., 46000.],
       [ 1911., 40300.,  8000., 46800.],
       [ 1912., 57000., 12300., 43800.],
       [ 1913., 76600., 19500., 40900.],
       [ 1914., 52300., 45700., 39400.],
       [ 1915., 19500., 51100., 39000.],
       [ 1916., 11200., 29700., 36700.],
       [ 1917.,  7600., 15800., 41800.],
       [ 1918., 14600.,  9700., 43300.],
       [ 1919., 16200., 10100., 41300.],
       [ 1920., 24700.,  8600., 47300.]])

In [43]:
## assign the headers to data and Transvers the data
year, hare, lynx, carrot = data.T

## Print the header value

print("Year Value : ",year)
print("hare Value : ",hare)
print("lynx Value : ",lynx)
print("carrot Value : ",carrot)

Year Value :  [1900. 1901. 1902. 1903. 1904. 1905. 1906. 1907. 1908. 1909. 1910. 1911.
 1912. 1913. 1914. 1915. 1916. 1917. 1918. 1919. 1920.]
hare Value :  [30000. 47200. 70200. 77400. 36300. 20600. 18100. 21400. 22000. 25400.
 27100. 40300. 57000. 76600. 52300. 19500. 11200.  7600. 14600. 16200.
 24700.]
lynx Value :  [ 4000.  6100.  9800. 35200. 59400. 41700. 19000. 13000.  8300.  9100.
  7400.  8000. 12300. 19500. 45700. 51100. 29700. 15800.  9700. 10100.
  8600.]
carrot Value :  [48300. 48200. 41500. 38200. 40600. 39800. 38600. 42300. 44500. 42100.
 46000. 46800. 43800. 40900. 39400. 39000. 36700. 41800. 43300. 41300.
 47300.]


In [44]:

##print("print population 1:",populations)
populations = data[:,1:] ## pick all rows and start second columns values
print("print population 2:",populations)


print population 2: [[30000.  4000. 48300.]
 [47200.  6100. 48200.]
 [70200.  9800. 41500.]
 [77400. 35200. 38200.]
 [36300. 59400. 40600.]
 [20600. 41700. 39800.]
 [18100. 19000. 38600.]
 [21400. 13000. 42300.]
 [22000.  8300. 44500.]
 [25400.  9100. 42100.]
 [27100.  7400. 46000.]
 [40300.  8000. 46800.]
 [57000. 12300. 43800.]
 [76600. 19500. 40900.]
 [52300. 45700. 39400.]
 [19500. 51100. 39000.]
 [11200. 29700. 36700.]
 [ 7600. 15800. 41800.]
 [14600.  9700. 43300.]
 [16200. 10100. 41300.]
 [24700.  8600. 47300.]]


In [45]:
np.max(populations,axis=1) ## Get the max value from data

array([48300., 48200., 70200., 77400., 59400., 41700., 38600., 42300.,
       44500., 42100., 46000., 46800., 57000., 76600., 52300., 51100.,
       36700., 41800., 43300., 41300., 47300.])

In [46]:
np.argmax(populations, axis=1) ## index value of maximum value from data

array([2, 2, 0, 0, 1, 1, 2, 2, 2, 2, 2, 2, 0, 0, 0, 1, 2, 2, 2, 2, 2],
      dtype=int64)

### Broadcasting / Tiles

In [48]:
### Create the Tiles if we don't have tiles

a = np.tile(np.arange(0,40,10),(3,1))
print("tile value a: ",a)
a = a.T
print(" After Transpose a: ",a)


b = np.array([0,1,2])
print("Array b", b)
print(" \nAdding two tiles : ",(a + b)) ## as a is tiles and b is array.. it will automatically convert the b to similar tiles  and adding it


tile value a:  [[ 0 10 20 30]
 [ 0 10 20 30]
 [ 0 10 20 30]]
 After Transpose a:  [[ 0  0  0]
 [10 10 10]
 [20 20 20]
 [30 30 30]]
Array b [0 1 2]
 
Adding two tiles :  [[ 0  1  2]
 [10 11 12]
 [20 21 22]
 [30 31 32]]


In [49]:
#### when 1 dimension array given but enhance it
a = np.arange(0,40,10)
print("a Shape:",a.shape)
print("a value: ",a)


a Shape: (4,)
a value:  [ 0 10 20 30]


In [50]:
a= a[:,np.newaxis]
print("a Shape:",a.shape)
print("a value: ",a)

a Shape: (4, 1)
a value:  [[ 0]
 [10]
 [20]
 [30]]


In [52]:
print("Vlue of A : \n",a)
print("Vlue of B : \n",b)
a + b

Vlue of A : 
 [[ 0]
 [10]
 [20]
 [30]]
Vlue of B : 
 [0 1 2]


array([[ 0,  1,  2],
       [10, 11, 12],
       [20, 21, 22],
       [30, 31, 32]])