In [122]:
import numpy as np
arr1 = np.array(10)
print( " the array of np.array(10 is :", arr1)
print( 'dimesnion of array arr1 :',arr1.ndim)

arr2 = np.array([2,30])
print( " the array of np.array(1,10) is :", arr2)
print( 'dimesnion of array arr2 :',arr2.ndim)

arr3 = np.array([[2,30], [4,5]])
print( " the array of np.array(1,10) is :", arr3)
print( 'dimesnion of array arr3 :',arr3.ndim)
 
arr3 = np.array([[[2,30], [4,5]],[[21,30], [41,5]]])
print( " the array of np.array(1,10) is :", arr3)
print( 'dimesnion of array arr3 :',arr3.ndim)

 the array of np.array(10 is : 10
dimesnion of array arr1 : 0
 the array of np.array(1,10) is : [ 2 30]
dimesnion of array arr2 : 1
 the array of np.array(1,10) is : [[ 2 30]
 [ 4  5]]
dimesnion of array arr3 : 2
 the array of np.array(1,10) is : [[[ 2 30]
  [ 4  5]]

 [[21 30]
  [41  5]]]
dimesnion of array arr3 : 3


In [123]:
from numpy import random
range1 = np.arange(1,10)
print (range1)

range2 = np.arange(1,10,2)
print (range2)


range3 = np.arange(1,100,2, dtype= 'i')
print(range3)
print(range3[4])

arr4 = np.random.randint(1,100)
print (arr4)

randomV = random.random(size=3)
print("randomV",randomV)
print(randomV[1:3])

[1 2 3 4 5 6 7 8 9]
[1 3 5 7 9]
[ 1  3  5  7  9 11 13 15 17 19 21 23 25 27 29 31 33 35 37 39 41 43 45 47
 49 51 53 55 57 59 61 63 65 67 69 71 73 75 77 79 81 83 85 87 89 91 93 95
 97 99]
9
67
randomV [0.96437648 0.49131992 0.2561016 ]
[0.49131992 0.2561016 ]


In [124]:
arrayVal = np.ones((3,3),dtype='float')
print("arrayVal ones array",arrayVal)
print("arrVal selected values",arrayVal[1:3,2])

arrayVal1 = np.zeros((3,3))
print("arraVal1 zero array", arrayVal1)


arrdiagonal = np.diag((1,2,3,4))
print("Diagonal Array \n" ,arrdiagonal)
print("Selected Values :", arrdiagonal[0:4,0:2])




arrayVal ones array [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
arrVal selected values [1. 1.]
arraVal1 zero array [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
Diagonal Array 
 [[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]
Selected Values : [[1 0]
 [0 2]
 [0 0]
 [0 0]]


In [125]:
## Broadcast the value

##Create dataframes from list
import pandas as pd
weatherData = [('1/1/2024', 8,41,'Sunny'),
 ('2/1/2024', 2,42,'Rainy'),
 ('3/1/2024', 8,45,'Sunny'),
 ('4/1/2024', 8,45,'Sunny'),
 ('5/1/2024', 3,45,'Rainy'),
 ('6/1/2024', 23,20,'Hot')
 ]

df = pd.DataFrame(weatherData, columns= ('Day','Temprature','Wind Speed', 'Event' ))

print(" DataFrame: \n", df)

 DataFrame: 
         Day  Temprature  Wind Speed  Event
0  1/1/2024           8          41  Sunny
1  2/1/2024           2          42  Rainy
2  3/1/2024           8          45  Sunny
3  4/1/2024           8          45  Sunny
4  5/1/2024           3          45  Rainy
5  6/1/2024          23          20    Hot


In [126]:
# Creating dataframes from array

df1 = pd.DataFrame(np.random.rand(20,7))
print("dataFrames \n:", df1)

dataFrames 
:            0         1         2         3         4         5         6
0   0.045372  0.058638  0.152502  0.606047  0.887455  0.521185  0.078512
1   0.449450  0.492538  0.377909  0.074556  0.589180  0.103275  0.017716
2   0.580642  0.580967  0.248603  0.048649  0.808648  0.005679  0.370171
3   0.720179  0.875797  0.975735  0.491581  0.845401  0.284170  0.374182
4   0.308791  0.904776  0.982523  0.446408  0.402785  0.704687  0.845693
5   0.519088  0.858734  0.618829  0.220567  0.494563  0.943800  0.932404
6   0.470589  0.923384  0.443768  0.566622  0.364964  0.788726  0.927420
7   0.877728  0.567419  0.826936  0.614249  0.964872  0.004851  0.581401
8   0.407015  0.519573  0.259073  0.913597  0.177750  0.211945  0.562240
9   0.289655  0.682446  0.104892  0.304287  0.687784  0.836082  0.633283
10  0.243406  0.147347  0.103920  0.032282  0.543061  0.436403  0.044233
11  0.035452  0.547391  0.504804  0.449386  0.377374  0.358598  0.736040
12  0.559830  0.215417  0.856318  0.0

In [127]:

abc = np.arange(10)
print ("Full Array :  \n",abc)
print("single Value : ", abc[1])



Full Array :  
 [0 1 2 3 4 5 6 7 8 9]
single Value :  1


In [128]:
a = np.arange(10)  ## slicing the data
b = np.arange(5)
print("Full Range Array  : \n",a)
a[5 :] = 100
print("After changing 5th Onward va;ue to 100 : \n ",a)

print(" selection from 2 to 9th element by step 2 : \n", a[2:9:2])

print("Actual value of b : \n",b)
print("Reverse value of b : \n",b[::-1])

a[5:] = b[::-1] ## assigning the element

print(" Actual value of a after change \n :",a )


Full Range Array  : 
 [0 1 2 3 4 5 6 7 8 9]
After changing 5th Onward va;ue to 100 : 
  [  0   1   2   3   4 100 100 100 100 100]
 selection from 2 to 9th element by step 2 : 
 [  2   4 100 100]
Actual value of b : 
 [0 1 2 3 4]
Reverse value of b : 
 [4 3 2 1 0]
 Actual value of a after change 
 : [0 1 2 3 4 4 3 2 1 0]


Shared Memory

In [129]:
a = np.arange(10)
print("a:",a)
print("Address a:",id(a))
b = a[::2]
print("b: ",b)
print("Address b:",id(b))
print(np.shares_memory(a,b))


## One element change will impact other array too
b[1] = 100
print("a:",a)
print("b: ",b)

a: [0 1 2 3 4 5 6 7 8 9]
Address a: 1454235024912
b:  [0 2 4 6 8]
Address b: 1454250588176
True
a: [  0   1 100   3   4   5   6   7   8   9]
b:  [  0 100   4   6   8]
