## Flattering of Array

In [90]:
import numpy as np 
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
print("Array : \n",arr)

## Array flattening the array in 1 D
print("Ravel Value: \n",arr.ravel())
print("Ravel Value  of A : \n", arr.ravel('A')) ## Change the array to 1D
print("Ravel Value  of C : \n",arr.ravel('C'))
print("Ravel Value  of F : \n",arr.ravel('F'))
print("Ravel Value  of K : \n",arr.ravel('K'))

print("Traversal  of Array: \n ",arr.T)
print("Traversal and Ravel \n",arr.T.ravel())




Array : 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Ravel Value: 
 [1 2 3 4 5 6 7 8 9]
Ravel Value  of A : 
 [1 2 3 4 5 6 7 8 9]
Ravel Value  of C : 
 [1 2 3 4 5 6 7 8 9]
Ravel Value  of F : 
 [1 4 7 2 5 8 3 6 9]
Ravel Value  of K : 
 [1 2 3 4 5 6 7 8 9]
Traversal  of Array: 
  [[1 4 7]
 [2 5 8]
 [3 6 9]]
Traversal and Ravel 
 [1 4 7 2 5 8 3 6 9]


In [ ]:
## Pandas in import
import pandas as pd
df = pd.read_csv("customers-100.csv")
print(df)


In [ ]:
## Pandas in import
import pandas as pd
df1 = pd.read_csv("customers-100.csv",header=None)
print(df1)

In [91]:
## Pandas in import
import pandas as pd
df2 = pd.read_csv("customers-100 WithoutHeader.csv",names=['Index','Customer Id''Last Name','First Name','Company','City','Country','Phone 1','Phone 2','Email','Subscription Date','WebsiteCity'])
print(df2)

               Index Customer IdLast Name First Name  \
1    DD37Cf93aecA6Dc               Sheryl     Baxter   
2    1Ef7b82A4CAAD10              Preston     Lozano   
3    6F94879bDAfE5a6                  Roy      Berry   
4    5Cef8BFA16c5e3c                Linda      Olsen   
5    053d585Ab6b3159               Joanna     Bender   
..               ...                  ...        ...   
96   cb8E23e48d22Eae                 Karl      Greer   
97   CeD220bdAaCfaDf                 Lynn   Atkinson   
98   28CDbC0dFe4b1Db                 Fred     Guerra   
99   c23d1D9EE8DEB0A               Yvonne     Farmer   
100  2354a0E336A91A1             Clarence     Haynes   

                             Company               City  \
1                    Rasmussen Group       East Leonard   
2                        Vega-Gentry  East Jimmychester   
3                      Murillo-Perry      Isabelborough   
4    Dominguez, Mcmillan and Donovan         Bensonview   
5           Martin, Lang and And

In [ ]:
## Pandas in import
import pandas as pd
df = pd.read_csv("customers-100.csv",sep='$') ## when sseprated by '$'
df


In [ ]:
## Pandas in import
import pandas as pd
df = pd.read_csv("customers-100.csv",sep='$', skiprows=[3,5]) ## when sseprated by '$' and skipp the rows
df



In [ ]:
type(df)

In [ ]:
df = pd.read_csv('Weather.csv')
df


In [ ]:
print("Data Types: \n",df.dtypes) ## Datatypes 
print("Columns: \n",df.columns) ## columns
print("Describe : \n",df.describe()) ## Provide the missing value details

In [ ]:
print(df.describe()) ## Provide the missing value details

In [ ]:
df['MinTemp']

In [ ]:
df['MinTemp'].min()  ## provide the minimum temprature

In [ ]:
type(df['MinTemp'])  ## datatype of single column

In [ ]:
df[['MaxTemp','MinTemp']] ## display value of Min and Max Temp

In [ ]:
type(df[['MaxTemp','MinTemp']]) ## type of two columns

In [ ]:
df['RainTomorrow'] ## Display Single column

In [ ]:
df['RainTomorrow']== 'Yes'   ## Compare the value within column Values and provide results

In [ ]:
df['Rainfall'][df['RainTomorrow']== 'Yes'] ## display the Rain fall value where Rain Tomorrow is "Yes"

In [ ]:
df['Rainfall'][df['RainTomorrow']=='Yes']==39.8 ## Display the Value True where RainTomorrow = 'Yes and Rain Fall  must be 39.8 
## provide inex and result

In [92]:

df['MaxTemp'][df['Rainfall']==39.8]==15.5  

KeyError: 'MaxTemp'

In [93]:
df2 = pd.read_csv('weather.csv')
df2.loc[(df2['Rainfall'] ==39.8) & (df2['RainTomorrow'] == 'Yes'), ('Pressure3pm','Sunshine')]

Pressure3pm  Sunshine
3       1007.0       9.1
8       1022.7       4.1

In [ ]:
import pandas as pd 
weatherData = [('1/1/2024', 8,45,'Sunny'),
 ('2/1/2024', 8,45,'Sunny'),
 ('3/1/2024', 8,45,'Sunny'),
 ('4/1/2024', 8,45,'Sunny'),
 ('5/1/2024', 3,45,'Rainy'),
 ('6/1/2024', 45,20,'Hot'),
 ('1/1/2024', 8,45,'Sunny'),
 ('2/1/2024', 8,45,'Sunny'),
 ('3/1/2024', 8,45,'Sunny'),
 ('4/1/2024', 8,45,'Sunny'),
 ('5/1/2024', 3,45,'Rainy'),
 ('6/1/2024', 45,20,'Hot'),
 ('1/1/2024', 8,45,'Sunny'),
 ('2/1/2024', 8,45,'Sunny'),
 ('3/1/2024', 8,45,'Sunny'),
 ('4/1/2024', 8,45,'Sunny'),
 ('5/1/2024', 3,45,'Rainy'),
 ('6/1/2024', 45,20,'Hot'),
 ('1/1/2024', 8,45,'Sunny'),
 ('2/1/2024', 8,45,'Sunny'),
 ('3/1/2024', 8,45,'Sunny'),
 ('4/1/2024', 8,45,'Sunny'),
 ('5/1/2024', 3,45,'Rainy'),
 ('6/1/2024', 45,20,'Hot'),
 ('1/1/2024', 8,45,'Sunny'),
 ('2/1/2024', 8,45,'Sunny'),
 ('3/1/2024', 8,45,'Sunny'),
 ('4/1/2024', 8,45,'Sunny'),
 ('5/1/2024', 3,45,'Rainy'),
 ('6/1/2024', 45,20,'Hot'),
 ('1/1/2024', 8,45,'Sunny'),
 ('2/1/2024', 8,45,'Sunny'),
 ('3/1/2024', 8,45,'Sunny'),
 ('4/1/2024', 8,45,'Sunny'),
 ('5/1/2024', 3,45,'Rainy'),
 ('6/1/2024', 60,20,'Hot')

 ]
df = pd.DataFrame(weatherData,columns=('Day','Temprature','Winspeed','Event'))
df

In [ ]:
df.head() # provide the first five rows 

In [ ]:
df.head(2) ##  to get first 2 rows

In [ ]:
df.tail() ## provide by defauly last 5 rows

In [ ]:
df.tail(2) ## Provide last 2 rows

In [ ]:
df[2:4] # slicing [start row : upto row]

In [ ]:
df.columns ## provide the columns of data frame

In [ ]:
df.Day  # provide value of particular columnDay

In [ ]:
df['Day'] # Column value of data frame

In [ ]:
df[['Day','Event','Temprature']]

In [ ]:
print("Maximum Temprature",df['Temprature'].max()) # Get the  max temprature
print("Row values which having Max temprature  ",df[df['Temprature']== df['Temprature'].max()]) # Get the row of the dataframe having max temprature

In [ ]:
import pandas as pd
df = pd.read_excel('weatherHistory.xlsx')
print(df)

In [ ]:
import pandas as pd
df = pd.read_excel('weatherHistoryCopy.xlsx',sheet_name='Sheet1') ## Read the particular sheet from excel file
print(df)

In [60]:
import pandas as pd 
weatherData = [('1/1/2024', 8,45,'Sunny'),
 ('2/1/2024', 8,45,'Sunny'),
 ('3/1/2024', 8,45,'Sunny'),
 ('4/1/2024', 8,45,'Sunny'),
 ('5/1/2024', 3,45,'Rainy'),
 ('6/1/2024', 45,20,'Hot')]



In [61]:
df = pd.DataFrame(weatherData,columns=['Day','Temp','Wind','Event'])

In [62]:
df

Day  Temp  Wind  Event
0  1/1/2024     8    45  Sunny
1  2/1/2024     8    45  Sunny
2  3/1/2024     8    45  Sunny
3  4/1/2024     8    45  Sunny
4  5/1/2024     3    45  Rainy
5  6/1/2024    45    20    Hot

In [63]:
df.to_csv('Demo.csv') # create scv from data frame


In [64]:
df.to_excel('NewExcel1.xlsx',sheet_name='weatherData') ## create excel with sheet name and with indexing

In [66]:
df.to_excel('NewExcel.xlsx',sheet_name='weatherData', index = False) ## create excel with sheet name and without indexing

In [67]:
df = pd.read_csv('city_temperature.csv') ## read csv file
df

Region       Country  State     City  Month  Day  Year  AvgTemperature
0       Africa       Algeria    NaN  Algiers      1    1  1995            64.2
1       Africa       Algeria    NaN  Algiers      1    2  1995            49.4
2       Africa       Algeria    NaN  Algiers      1    3  1995            48.8
3       Africa       Algeria    NaN  Algiers      1    4  1995            46.4
4       Africa       Algeria    NaN  Algiers      1    5  1995            47.9
...        ...           ...    ...      ...    ...  ...   ...             ...
546514    Asia  Turkmenistan    NaN  Ashabad     11   18  2012            49.2
546515    Asia  Turkmenistan    NaN  Ashabad     11   19  2012            43.9
546516    Asia  Turkmenistan    NaN  Ashabad     11   20  2012            40.7
546517    Asia  Turkmenistan    NaN  Ashabad     11   21  2012            34.8
546518    Asia  Turkmenistan    NaN  Ashabad     11   22  2012            35.9

[546519 rows x 8 columns]

In [68]:
## to describe the data city wise (group by)
g = df.groupby('City')
g

In [70]:
for City, City_df in g:  ## (Print the City group and dataframe of each group  )
    print(City)
    print(City_df)

Abidjan
        Region      Country  State     City  Month  Day  Year  AvgTemperature
96499   Africa  Ivory Coast    NaN  Abidjan      1    1  1995            82.6
96500   Africa  Ivory Coast    NaN  Abidjan      1    2  1995            82.3
96501   Africa  Ivory Coast    NaN  Abidjan      1    3  1995            81.0
96502   Africa  Ivory Coast    NaN  Abidjan      1    4  1995            83.3
96503   Africa  Ivory Coast    NaN  Abidjan      1    5  1995            83.4
...        ...          ...    ...      ...    ...  ...   ...             ...
105760  Africa  Ivory Coast    NaN  Abidjan      5    9  2020            84.6
105761  Africa  Ivory Coast    NaN  Abidjan      5   10  2020            84.4
105762  Africa  Ivory Coast    NaN  Abidjan      5   11  2020            78.3
105763  Africa  Ivory Coast    NaN  Abidjan      5   12  2020            82.1
105764  Africa  Ivory Coast    NaN  Abidjan      5   13  2020            81.3

[9266 rows x 8 columns]
Addis Ababa
       Region   Cou

In [71]:
group2 = df.groupby('Region')
for Region, Region_df in group2:  ## (Print the Region and  group  and dataframe of each group  ) here v is defined variables
    print(Region)
    print(Region_df)

Africa
        Region  Country  State     City  Month  Day  Year  AvgTemperature
0       Africa  Algeria    NaN  Algiers      1    1  1995            64.2
1       Africa  Algeria    NaN  Algiers      1    2  1995            49.4
2       Africa  Algeria    NaN  Algiers      1    3  1995            48.8
3       Africa  Algeria    NaN  Algiers      1    4  1995            46.4
4       Africa  Algeria    NaN  Algiers      1    5  1995            47.9
...        ...      ...    ...      ...    ...  ...   ...             ...
251113  Africa   Zambia    NaN   Lusaka      1   18  2014            71.3
251114  Africa   Zambia    NaN   Lusaka      1   19  2014            77.5
251115  Africa   Zambia    NaN   Lusaka      1   20  2014            73.4
251116  Africa   Zambia    NaN   Lusaka      1   21  2014            73.1
251117  Africa   Zambia    NaN   Lusaka      1   22  2014            71.3

[251118 rows x 8 columns]
Asia
       Region       Country  State     City  Month  Day  Year  AvgTempera

In [72]:
## Get the frame of the single group from multiple groups
g.get_group('Abidjan')

Region      Country  State     City  Month  Day  Year  AvgTemperature
96499   Africa  Ivory Coast    NaN  Abidjan      1    1  1995            82.6
96500   Africa  Ivory Coast    NaN  Abidjan      1    2  1995            82.3
96501   Africa  Ivory Coast    NaN  Abidjan      1    3  1995            81.0
96502   Africa  Ivory Coast    NaN  Abidjan      1    4  1995            83.3
96503   Africa  Ivory Coast    NaN  Abidjan      1    5  1995            83.4
...        ...          ...    ...      ...    ...  ...   ...             ...
105760  Africa  Ivory Coast    NaN  Abidjan      5    9  2020            84.6
105761  Africa  Ivory Coast    NaN  Abidjan      5   10  2020            84.4
105762  Africa  Ivory Coast    NaN  Abidjan      5   11  2020            78.3
105763  Africa  Ivory Coast    NaN  Abidjan      5   12  2020            82.1
105764  Africa  Ivory Coast    NaN  Abidjan      5   13  2020            81.3

[9266 rows x 8 columns]

In [73]:
Abidjan = g.get_group('Abidjan').describe  ## print group of the group
Abidjan

<bound method NDFrame.describe of         Region      Country  State     City  Month  Day  Year  AvgTemperature
96499   Africa  Ivory Coast    NaN  Abidjan      1    1  1995            82.6
96500   Africa  Ivory Coast    NaN  Abidjan      1    2  1995            82.3
96501   Africa  Ivory Coast    NaN  Abidjan      1    3  1995            81.0
96502   Africa  Ivory Coast    NaN  Abidjan      1    4  1995            83.3
96503   Africa  Ivory Coast    NaN  Abidjan      1    5  1995            83.4
...        ...          ...    ...      ...    ...  ...   ...             ...
105760  Africa  Ivory Coast    NaN  Abidjan      5    9  2020            84.6
105761  Africa  Ivory Coast    NaN  Abidjan      5   10  2020            84.4
105762  Africa  Ivory Coast    NaN  Abidjan      5   11  2020            78.3
105763  Africa  Ivory Coast    NaN  Abidjan      5   12  2020            82.1
105764  Africa  Ivory Coast    NaN  Abidjan      5   13  2020            81.3

[9266 rows x 8 columns]>

In [74]:
g.get_group('Abidjan').get('Region') ## Get the Region Value only

96499     Africa
96500     Africa
96501     Africa
96502     Africa
96503     Africa
           ...  
105760    Africa
105761    Africa
105762    Africa
105763    Africa
105764    Africa
Name: Region, Length: 9266, dtype: object

In [75]:
g.get_group('Abidjan')['AvgTemperature'].max() ## get the max temprature from group

88.6

In [76]:
df3 = g.get_group('Abidjan') ## grt the frame by group by
for col in  df3.columns:
    print('\n ', col)
    print(df3[col].unique())


  Region
['Africa']

  Country
['Ivory Coast']

  State
[nan]

  City
['Abidjan']

  Month
[ 1  2  3  4  5  6  7  8  9 10 11 12]

  Day
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31]

  Year
[1995 1996 1997 1998 1999 2000 2001 2002 2003 2004 2005 2006 2007 2008
 2009 2010 2011 2012 2013 2014 2015 2016 2017 2018 2019 2020]

  AvgTemperature
[ 82.6  82.3  81.   83.3  83.4  84.1  82.5  81.3  79.7  80.9  77.5  73.8
  73.   74.9  76.7  78.9  80.1  80.3  79.   75.7  78.3  77.   82.4  79.8
  80.8  81.1  81.6  80.4  83.   82.7  82.2  82.9  81.8  81.9  83.1  83.6
  83.2  84.7  84.6  84.5  84.8  84.3  84.   84.2  83.9  82.8  81.4  83.7
  77.8  81.7  83.8  86.1  85.1  84.9  85.9  86.   86.7  76.9  83.5  79.5
  84.4  80.6  81.2  85.2  82.   79.1  79.2  79.6  78.7  79.9  81.5  82.1
  79.4  80.5  79.3  74.4  78.5  80.   80.2  77.9  78.8  78.4  78.1  77.1
  75.5  76.2  77.3  77.2  76.5  78.6  77.7  74.5  77.6  78.2  78.   76.8
  75.8 -99.   75.9  76.1

In [77]:
## Merging and Concate

india_Weather = pd.DataFrame({'City':['Mumbai','Delhi', 'Chandigarh'], 'Temperature': [32, 35,30], 'Humidity': [68,65,79]})
india_Weather

City  Temperature  Humidity
0      Mumbai           32        68
1       Delhi           35        65
2  Chandigarh           30        79

In [78]:
us_Weather = pd.DataFrame({'City':['New york','Chicago', 'Orland'], 'Temperature': [21, 14,23], 'Humidity': [68,65,75]})
us_Weather

City  Temperature  Humidity
0  New york           21        68
1   Chicago           14        65
2    Orland           23        75

In [79]:
df =pd.concat([india_Weather, us_Weather], ignore_index= True)
df

City  Temperature  Humidity
0      Mumbai           32        68
1       Delhi           35        65
2  Chandigarh           30        79
3    New york           21        68
4     Chicago           14        65
5      Orland           23        75

In [80]:
df =pd.concat([india_Weather, us_Weather], axis= 1) ## concate column wise
df

City  Temperature  Humidity      City  Temperature  Humidity
0      Mumbai           32        68  New york           21        68
1       Delhi           35        65   Chicago           14        65
2  Chandigarh           30        79    Orland           23        75

In [81]:
df = pd.merge(india_Weather, us_Weather, on='Humidity',how='outer') ## merge the dataframe and add value Nan where data missing
df

City_x  Temperature_x  Humidity    City_y  Temperature_y
0       Delhi           35.0        65   Chicago           14.0
1      Mumbai           32.0        68  New york           21.0
2         NaN            NaN        75    Orland           23.0
3  Chandigarh           30.0        79       NaN            NaN

In [84]:
df = pd.merge(india_Weather, us_Weather, on='Humidity',how='inner') ## merge the dataframe which are matching, act like inner join
df

City_x  Temperature_x  Humidity    City_y  Temperature_y
0  Mumbai             32        68  New york             21
1   Delhi             35        65   Chicago             14

In [85]:
df = pd.merge(india_Weather, us_Weather, on='Humidity',how='left') ## merge the dataframe which are matching, act like left join
df

City_x  Temperature_x  Humidity    City_y  Temperature_y
0      Mumbai             32        68  New york           21.0
1       Delhi             35        65   Chicago           14.0
2  Chandigarh             30        79       NaN            NaN

In [86]:
df = pd.merge(india_Weather, us_Weather, on='Humidity',how='right') ## merge the dataframe which are matching, act like right join
df

City_x  Temperature_x  Humidity    City_y  Temperature_y
0  Mumbai           32.0        68  New york             21
1   Delhi           35.0        65   Chicago             14
2     NaN            NaN        75    Orland             23

In [87]:
df = pd.read_csv('city_temperature.csv', index_col='AvgTemperature')
df


Region       Country  State     City  Month  Day  Year
AvgTemperature                                                        
64.2            Africa       Algeria    NaN  Algiers      1    1  1995
49.4            Africa       Algeria    NaN  Algiers      1    2  1995
48.8            Africa       Algeria    NaN  Algiers      1    3  1995
46.4            Africa       Algeria    NaN  Algiers      1    4  1995
47.9            Africa       Algeria    NaN  Algiers      1    5  1995
...                ...           ...    ...      ...    ...  ...   ...
49.2              Asia  Turkmenistan    NaN  Ashabad     11   18  2012
43.9              Asia  Turkmenistan    NaN  Ashabad     11   19  2012
40.7              Asia  Turkmenistan    NaN  Ashabad     11   20  2012
34.8              Asia  Turkmenistan    NaN  Ashabad     11   21  2012
35.9              Asia  Turkmenistan    NaN  Ashabad     11   22  2012

[546519 rows x 7 columns]

In [88]:
df.loc[48.8] # print the rows which having values 48.8

Region       Country  State     City  Month  Day  Year
AvgTemperature                                                        
48.8            Africa       Algeria    NaN  Algiers      1    3  1995
48.8            Africa       Algeria    NaN  Algiers      2    5  1995
48.8            Africa       Algeria    NaN  Algiers      2   24  1998
48.8            Africa       Algeria    NaN  Algiers      1   18  2000
48.8            Africa       Algeria    NaN  Algiers      2   25  2000
...                ...           ...    ...      ...    ...  ...   ...
48.8              Asia  Turkmenistan    NaN  Ashabad     11    9  2005
48.8              Asia  Turkmenistan    NaN  Ashabad      2   13  2006
48.8              Asia  Turkmenistan    NaN  Ashabad     11   11  2006
48.8              Asia  Turkmenistan    NaN  Ashabad      1   30  2007
48.8              Asia  Turkmenistan    NaN  Ashabad      2   20  2008

[241 rows x 7 columns]

In [89]:
df.iloc[2] # pick the row on the index 2

Region      Africa
Country    Algeria
State          NaN
City       Algiers
Month            1
Day              3
Year          1995
Name: 48.8, dtype: object