In [5]:
### array Traversal and Revel
import numpy as np
import pandas as pd

array1 = np.array([[1,2,3],[4,5,6],[6,7,8]])
print ("Array : \n",array1)
print("array shape : ",array1.shape)
print("Convert the array in 1D using Array ravel :\n",array1.ravel())
print("Traverse of Array :\n",array1.T)
print(" Traverse and then Revel of array :",array1.T.ravel())

Array : 
 [[1 2 3]
 [4 5 6]
 [6 7 8]]
array shape :  (3, 3)
Convert the array in 1D using Array ravel :
 [1 2 3 4 5 6 6 7 8]
Traverse of Array :
 [[1 4 6]
 [2 5 7]
 [3 6 8]]
 Traverse and then Revel of array : [1 4 6 2 5 7 3 6 8]


In [6]:
## Read CSV using Pandas
dataFrame1 = pd.read_csv('customers-100 For Excercise.csv') ## Read the CSV with headers
print (dataFrame1)


    Index      Customer Id First Name Last Name  \
0       1  DD37Cf93aecA6Dc     Sheryl    Baxter   
1       2  1Ef7b82A4CAAD10    Preston    Lozano   
2       3  6F94879bDAfE5a6        Roy     Berry   
3       4  5Cef8BFA16c5e3c      Linda     Olsen   
4       5  053d585Ab6b3159     Joanna    Bender   
..    ...              ...        ...       ...   
95     96  cb8E23e48d22Eae       Karl     Greer   
96     97  CeD220bdAaCfaDf       Lynn  Atkinson   
97     98  28CDbC0dFe4b1Db       Fred    Guerra   
98     99  c23d1D9EE8DEB0A     Yvonne    Farmer   
99    100  2354a0E336A91A1   Clarence    Haynes   

                            Company               City  \
0                   Rasmussen Group       East Leonard   
1                       Vega-Gentry  East Jimmychester   
2                     Murillo-Perry      Isabelborough   
3   Dominguez, Mcmillan and Donovan         Bensonview   
4          Martin, Lang and Andrade     West Priscilla   
..                              ...    

In [7]:
## Pandas in import
import pandas as pd
dataFrame2 = pd.read_csv("customers-100 For Excercise.csv", header= None) ## Read the CSV with headers
print (dataFrame2)

        0                1           2          3   \
0    Index      Customer Id  First Name  Last Name   
1        1  DD37Cf93aecA6Dc      Sheryl     Baxter   
2        2  1Ef7b82A4CAAD10     Preston     Lozano   
3        3  6F94879bDAfE5a6         Roy      Berry   
4        4  5Cef8BFA16c5e3c       Linda      Olsen   
..     ...              ...         ...        ...   
96      96  cb8E23e48d22Eae        Karl      Greer   
97      97  CeD220bdAaCfaDf        Lynn   Atkinson   
98      98  28CDbC0dFe4b1Db        Fred     Guerra   
99      99  c23d1D9EE8DEB0A      Yvonne     Farmer   
100    100  2354a0E336A91A1    Clarence     Haynes   

                                  4                  5                    6   \
0                            Company               City              Country   
1                    Rasmussen Group       East Leonard                Chile   
2                        Vega-Gentry  East Jimmychester             Djibouti   
3                      Murillo-

In [8]:
import pandas as pd
dataFrame3 = pd.read_csv("customers-100 WithoutHeader.csv",names=['Index','Customer Id''Last Name','First Name','Company','City','Country','Phone 1','Phone 2','Email','Subscription Date','WebsiteCity'])
print(dataFrame3)

               Index Customer IdLast Name First Name  \
1    DD37Cf93aecA6Dc               Sheryl     Baxter   
2    1Ef7b82A4CAAD10              Preston     Lozano   
3    6F94879bDAfE5a6                  Roy      Berry   
4    5Cef8BFA16c5e3c                Linda      Olsen   
5    053d585Ab6b3159               Joanna     Bender   
..               ...                  ...        ...   
96   cb8E23e48d22Eae                 Karl      Greer   
97   CeD220bdAaCfaDf                 Lynn   Atkinson   
98   28CDbC0dFe4b1Db                 Fred     Guerra   
99   c23d1D9EE8DEB0A               Yvonne     Farmer   
100  2354a0E336A91A1             Clarence     Haynes   

                             Company               City  \
1                    Rasmussen Group       East Leonard   
2                        Vega-Gentry  East Jimmychester   
3                      Murillo-Perry      Isabelborough   
4    Dominguez, Mcmillan and Donovan         Bensonview   
5           Martin, Lang and And

In [9]:
dataFrame4 = pd.read_csv("customers-100.csv",sep='$',skiprows=[2,4])
print(dataFrame4)

    Index      Customer Id First Name Last Name                       Company  \
0       1  DD37Cf93aecA6Dc     Sheryl    Baxter               Rasmussen Group   
1       3  6F94879bDAfE5a6        Roy     Berry                 Murillo-Perry   
2       5  053d585Ab6b3159     Joanna    Bender      Martin$ Lang and Andrade   
3       6  2d08FB17EE273F4      Aimee     Downs                  Steele Group   
4       7  EA4d384DfDbBf77     Darren      Peck  Lester$ Woodard and Mitchell   
..    ...              ...        ...       ...                           ...   
93     96  cb8E23e48d22Eae       Karl     Greer                     Carey LLC   
94     97  CeD220bdAaCfaDf       Lynn  Atkinson         Ware$ Burns and Oneal   
95     98  28CDbC0dFe4b1Db       Fred    Guerra                 Schmitt-Jones   
96     99  c23d1D9EE8DEB0A     Yvonne    Farmer            Fitzgerald-Harrell   
97    100  2354a0E336A91A1   Clarence    Haynes            Le$ Nash and Cross   

               City        

In [10]:
dataFrame5 = pd.read_csv("weather.csv")
print(dataFrame5)
print("Columns :\n",dataFrame5.columns)
print("Type :\n",type(dataFrame5))


     MinTemp  MaxTemp  Rainfall  Evaporation  Sunshine WindGustDir  \
0        8.0     24.3       0.0          3.4       6.3          NW   
1       14.0     26.9       3.6          4.4       9.7         ENE   
2       13.7     23.4       3.6          5.8       3.3          NW   
3       13.3     15.5      39.8          7.2       9.1          NW   
4        7.6     16.1       2.8          5.6      10.6         SSE   
..       ...      ...       ...          ...       ...         ...   
361      9.0     30.7       0.0          7.6      12.1         NNW   
362      7.1     28.4       0.0         11.6      12.7           N   
363     12.5     19.9       0.0          8.4       5.3         ESE   
364     12.5     26.9       0.0          5.0       7.1          NW   
365     12.3     30.2       0.0          6.0      12.6          NW   

     WindGustSpeed WindDir9am WindDir3pm  WindSpeed9am  ...  Humidity3pm  \
0             30.0         SW         NW           6.0  ...           29   
1      

In [11]:
print("Describe : ",dataFrame5.describe())

Describe :            MinTemp     MaxTemp    Rainfall  Evaporation    Sunshine  \
count  366.000000  366.000000  366.000000   366.000000  363.000000   
mean     7.265574   20.581421    1.537158     4.521858    7.909366   
std      6.025800    6.753401    4.676949     2.669383    3.481517   
min     -5.300000    7.600000    0.000000     0.200000    0.000000   
25%      2.300000   15.025000    0.000000     2.200000    5.950000   
50%      7.450000   19.650000    0.000000     4.200000    8.600000   
75%     12.500000   25.500000    0.200000     6.400000   10.500000   
max     20.900000   39.800000   39.800000    13.800000   13.600000   

       WindGustSpeed  WindSpeed9am  WindSpeed3pm  Humidity9am  Humidity3pm  \
count     364.000000    359.000000    366.000000   366.000000   366.000000   
mean       39.840659      9.651811     17.986339    72.035519    44.519126   
std        13.059807      7.951929      8.856997    13.137058    16.850947   
min        13.000000      0.000000      0.000

In [12]:
print("Max Temp Values: \n",dataFrame5['MaxTemp'])
print("Maximum value in Max Temp Values: \n",dataFrame5['MaxTemp'].max())



Max Temp Values: 
 0      24.3
1      26.9
2      23.4
3      15.5
4      16.1
       ... 
361    30.7
362    28.4
363    19.9
364    26.9
365    30.2
Name: MaxTemp, Length: 366, dtype: float64
Maximum value in Max Temp Values: 
 39.8


In [13]:
print("Min Temp Values: \n",dataFrame5['MinTemp'])
print("Type: \n",type(dataFrame5['MinTemp']))
print("Minimum value in Min Temp Values: \n",dataFrame5['MinTemp'].min())
print("Maximum value in Min Temp Values: \n",dataFrame5['MinTemp'].max())

Min Temp Values: 
 0       8.0
1      14.0
2      13.7
3      13.3
4       7.6
       ... 
361     9.0
362     7.1
363    12.5
364    12.5
365    12.3
Name: MinTemp, Length: 366, dtype: float64
Type: 
 <class 'pandas.core.series.Series'>
Minimum value in Min Temp Values: 
 -5.3
Maximum value in Min Temp Values: 
 20.9


In [14]:
print(dataFrame5[['MaxTemp','MinTemp']])

     MaxTemp  MinTemp
0       24.3      8.0
1       26.9     14.0
2       23.4     13.7
3       15.5     13.3
4       16.1      7.6
..       ...      ...
361     30.7      9.0
362     28.4      7.1
363     19.9     12.5
364     26.9     12.5
365     30.2     12.3

[366 rows x 2 columns]


In [15]:
print(dataFrame5[['MinTemp','MaxTemp']])
print(type(dataFrame5[['MaxTemp','MinTemp']]))

     MinTemp  MaxTemp
0        8.0     24.3
1       14.0     26.9
2       13.7     23.4
3       13.3     15.5
4        7.6     16.1
..       ...      ...
361      9.0     30.7
362      7.1     28.4
363     12.5     19.9
364     12.5     26.9
365     12.3     30.2

[366 rows x 2 columns]
<class 'pandas.core.frame.DataFrame'>


In [16]:

dataFrame5.loc[(dataFrame5['MaxTemp'] == 15.5) & (dataFrame5['Rainfall']== 39.8)]   ###Access a group of rows and columns by label(s) or a boolean array..loc[] is primarily label based, but may also be used with a boolean array.

dataFrame5.loc[(dataFrame5['MaxTemp'] == 15.5) & (dataFrame5['Rainfall']== 39.8),['Pressure9am','Pressure3pm']]   ###Access a group of rows and columns by label(s) or a boolean array..loc[] is primarily label based, but may also be used with a boolean array.


Pressure9am  Pressure3pm
3       1005.5       1007.0

In [17]:
dataFrame5['MaxTemp'].gt(30.0)
dataFrame5['Rainfall'].describe()
dataFrame5['RainTomorrow']=='Yes'

dataFrame5.loc[(dataFrame5['RainTomorrow']=='Yes')&(dataFrame5['RainToday']=='Yes')]

MinTemp  MaxTemp  Rainfall  Evaporation  Sunshine WindGustDir  \
1       14.0     26.9       3.6          4.4       9.7         ENE   
2       13.7     23.4       3.6          5.8       3.3          NW   
3       13.3     15.5      39.8          7.2       9.1          NW   
30      15.1     20.4      22.6          2.4       0.2         SSE   
45      15.5     21.1       5.4          6.4       0.9           S   
49      12.6     23.1       3.4          1.6       2.3         NNW   
50      14.8     29.5       6.4          1.8       8.1           N   
51      19.9     22.0      11.0          4.4       5.9         NNW   
79      15.3     19.6      18.8          5.0       0.0          NE   
91      17.6     27.8       5.2         10.2       3.6         ESE   
95      18.2     22.6       1.8          8.0       0.0         ENE   
103     14.5     24.2       4.4          6.6       5.9           W   
112     16.3     24.8       1.8          7.8       3.8           S   
145     13.1     17.4       6.4          2.8       0.0         NNW   
164      7.1     19.8       2.0          3.2       7.7           W   
207      4.7     18.5       3.8          2.0       5.1         ESE   
222      8.6     13.7       6.2          2.2       0.0          NW   
304      6.1     17.2       4.0          2.2       2.4          NW   
318     13.1     19.4       9.8          8.8       6.0         NNW   
319      8.7     19.7       1.6          5.2       8.0          NW   
338     14.4     20.7       7.6          9.4       4.9         NNW   

     WindGustSpeed WindDir9am WindDir3pm  WindSpeed9am  ...  Humidity3pm  \
1             39.0          E          W           4.0  ...           36   
2             85.0          N        NNE           6.0  ...           69   
3             54.0        WNW          W          30.0  ...           56   
30            41.0          E          S           6.0  ...           90   
45            31.0        SSE         NE           6.0  ...           86   
49            30.0          N         NW           4.0  ...           74   
50            41.0         NW         NW           6.0  ...           48   
51            76.0          N        WNW          41.0  ...           62   
79            33.0        SSE        NNE           9.0  ...           88   
91            39.0          N        NNW          13.0  ...           49   
95            33.0        SSE        ENE           7.0  ...           76   
103           48.0        NNW        WNW           9.0  ...           60   
112           50.0        NNW          N           4.0  ...           56   
145           43.0          N          N          11.0  ...           93   
164           39.0        SSE         NW          13.0  ...           56   
207           22.0        NNW          W           6.0  ...           50   
222           31.0          E        NaN           2.0  ...           94   
304           59.0         NW        WNW          24.0  ...           85   
318           67.0          N         NW          39.0  ...           43   
319           98.0         NW        NNW          31.0  ...           33   
338           33.0        NNW        NNW          20.0  ...           65   

     Pressure9am  Pressure3pm  Cloud9am  Cloud3pm  Temp9am  Temp3pm  \
1         1012.4       1008.4         5         3     17.5     25.7   
2         1009.5       1007.2         8         7     15.4     20.2   
3         1005.5       1007.0         2         7     13.5     14.1   
30        1015.0       1014.1         8         8     17.0     16.3   
45        1010.1       1008.6         8         8     16.6     20.0   
49        1015.8       1014.1         8         7     15.3     20.4   
50        1012.9       1008.3         2         7     21.0     28.2   
51         996.5        996.8         8         3     20.6     19.6   
79        1008.7       1006.0         8         8     18.0     18.6   
91        1014.6       1012.8         7         8     21.4     26.3   
95        

In [18]:
dataFrame5[['MaxTemp','MinTemp']]

MaxTemp  MinTemp
0       24.3      8.0
1       26.9     14.0
2       23.4     13.7
3       15.5     13.3
4       16.1      7.6
..       ...      ...
361     30.7      9.0
362     28.4      7.1
363     19.9     12.5
364     26.9     12.5
365     30.2     12.3

[366 rows x 2 columns]

In [19]:
import pandas as pd 
weatherData = [('1/1/2024', 8,45,'Sunny'), ('2/1/2024', 8,45,'Sunny'), ('3/1/2024', 8,45,'Sunny'), ('4/1/2024', 8,45,'Sunny'), ('5/1/2024', 3,45,'Rainy'), ('6/1/2024', 45,20,'Hot'), ('1/1/2024', 8,45,'Sunny'), ('2/1/2024', 8,45,'Sunny'), ('3/1/2024', 8,45,'Sunny'), ('4/1/2024', 8,45,'Sunny'), ('5/1/2024', 3,45,'Rainy'), ('6/1/2024', 45,20,'Hot'), ('1/1/2024', 8,45,'Sunny'), ('2/1/2024', 8,45,'Sunny'), ('3/1/2024', 8,45,'Sunny'), ('4/1/2024', 8,45,'Sunny'), ('5/1/2024', 3,45,'Rainy'), ('6/1/2024', 45,20,'Hot'), ('1/1/2024', 8,45,'Sunny'), ('2/1/2024', 8,45,'Sunny'), ('3/1/2024', 8,45,'Sunny'), ('4/1/2024', 8,45,'Sunny'),('5/1/2024', 3,45,'Rainy'), ('6/1/2024', 45,20,'Hot'), ('1/1/2024', 8,45,'Sunny'), ('2/1/2024', 8,45,'Sunny'), ('3/1/2024', 8,45,'Sunny'), ('4/1/2024', 8,45,'Sunny'), ('5/1/2024', 3,45,'Rainy'), ('6/1/2024', 45,20,'Hot'), ('1/1/2024', 8,45,'Sunny'), ('2/1/2024', 8,45,'Sunny'), ('3/1/2024', 8,45,'Sunny'), ('4/1/2024', 8,45,'Sunny'), ('5/1/2024', 3,45,'Rainy'), ('6/1/2024', 60,20,'Hot') ]

dataFrame6 = pd.DataFrame(weatherData,columns = ('Day','Temprature','Winspeed','Event'))
print(dataFrame6)
print(dataFrame6.describe())


         Day  Temprature  Winspeed  Event
0   1/1/2024           8        45  Sunny
1   2/1/2024           8        45  Sunny
2   3/1/2024           8        45  Sunny
3   4/1/2024           8        45  Sunny
4   5/1/2024           3        45  Rainy
5   6/1/2024          45        20    Hot
6   1/1/2024           8        45  Sunny
7   2/1/2024           8        45  Sunny
8   3/1/2024           8        45  Sunny
9   4/1/2024           8        45  Sunny
10  5/1/2024           3        45  Rainy
11  6/1/2024          45        20    Hot
12  1/1/2024           8        45  Sunny
13  2/1/2024           8        45  Sunny
14  3/1/2024           8        45  Sunny
15  4/1/2024           8        45  Sunny
16  5/1/2024           3        45  Rainy
17  6/1/2024          45        20    Hot
18  1/1/2024           8        45  Sunny
19  2/1/2024           8        45  Sunny
20  3/1/2024           8        45  Sunny
21  4/1/2024           8        45  Sunny
22  5/1/2024           3        45

In [20]:
print("Head function provide first five Rows:\n",dataFrame6.head())
print("To get first 2 rows using Head function: \n",dataFrame6.head(2))

print("Tail function provide last five Rows:\n",dataFrame6.tail())
print("To get last 2 rows using Tail function: \n",dataFrame6.tail(2))

Head function provide first five Rows:
         Day  Temprature  Winspeed  Event
0  1/1/2024           8        45  Sunny
1  2/1/2024           8        45  Sunny
2  3/1/2024           8        45  Sunny
3  4/1/2024           8        45  Sunny
4  5/1/2024           3        45  Rainy
To get first 2 rows using Head function: 
         Day  Temprature  Winspeed  Event
0  1/1/2024           8        45  Sunny
1  2/1/2024           8        45  Sunny
Tail function provide last five Rows:
          Day  Temprature  Winspeed  Event
31  2/1/2024           8        45  Sunny
32  3/1/2024           8        45  Sunny
33  4/1/2024           8        45  Sunny
34  5/1/2024           3        45  Rainy
35  6/1/2024          60        20    Hot
To get last 2 rows using Tail function: 
          Day  Temprature  Winspeed  Event
34  5/1/2024           3        45  Rainy
35  6/1/2024          60        20    Hot


In [27]:
print("Minimum Value : \n",dataFrame6['Temprature'].min())
print("Type :\n",type(dataFrame6['Temprature'].min()))
print("dataFrame Values",dataFrame6['Temprature'].values)
dataFrame6[(dataFrame6['Temprature']==dataFrame6['Temprature'].min()) & (dataFrame6['Event']!= 'Rainy')]

Minimum Value : 
 3
Type :
 <class 'numpy.int64'>
dataFrame Values [ 8  8  8  8  3 45  8  8  8  8  3 45  8  8  8  8  3 45  8  8  8  8  3 45
  8  8  8  8  3 45  8  8  8  8  3 60]


Empty DataFrame
Columns: [Day, Temprature, Winspeed, Event]
Index: []

In [31]:
# dataFrame6[dataFrame6['Event'] == 'Hot']
# dataFrame6['Temprature'] == 60  
print(dataFrame6[(dataFrame6['Event'] == 'Hot') & (dataFrame6['Temprature'] == 60 )])
dataFrame6[(dataFrame6['Event'] == 'Hot') & (dataFrame6['Temprature'] == 60 )].to_csv('Day6dataFramePractice.csv')
dataFrame6[(dataFrame6['Event'] == 'Hot') & (dataFrame6['Temprature'] == 60 )].to_excel('Day6dataFrameSelfPractice.xlsx',sheet_name='WeatherData', index= False)

         Day  Temprature  Winspeed Event
35  6/1/2024          60        20   Hot


In [37]:
dataframe8 = pd.read_csv('city_temperature.csv') ## read csv file
print("DataFrame for City Temprature : \n",dataframe8)
group1 = dataframe8.groupby('City') 
print("Group1:\n ",group1)
print("Describe Values : \n",group1.describe())



DataFrame for City Temprature : 
         Region       Country  State     City  Month  Day  Year  AvgTemperature
0       Africa       Algeria    NaN  Algiers      1    1  1995            64.2
1       Africa       Algeria    NaN  Algiers      1    2  1995            49.4
2       Africa       Algeria    NaN  Algiers      1    3  1995            48.8
3       Africa       Algeria    NaN  Algiers      1    4  1995            46.4
4       Africa       Algeria    NaN  Algiers      1    5  1995            47.9
...        ...           ...    ...      ...    ...  ...   ...             ...
546514    Asia  Turkmenistan    NaN  Ashabad     11   18  2012            49.2
546515    Asia  Turkmenistan    NaN  Ashabad     11   19  2012            43.9
546516    Asia  Turkmenistan    NaN  Ashabad     11   20  2012            40.7
546517    Asia  Turkmenistan    NaN  Ashabad     11   21  2012            34.8
546518    Asia  Turkmenistan    NaN  Ashabad     11   22  2012            35.9

[546519 rows x 8 

In [38]:
for city, city_df in group1:
    print(city)
    print(city_df)

Abidjan
        Region      Country  State     City  Month  Day  Year  AvgTemperature
96499   Africa  Ivory Coast    NaN  Abidjan      1    1  1995            82.6
96500   Africa  Ivory Coast    NaN  Abidjan      1    2  1995            82.3
96501   Africa  Ivory Coast    NaN  Abidjan      1    3  1995            81.0
96502   Africa  Ivory Coast    NaN  Abidjan      1    4  1995            83.3
96503   Africa  Ivory Coast    NaN  Abidjan      1    5  1995            83.4
...        ...          ...    ...      ...    ...  ...   ...             ...
105760  Africa  Ivory Coast    NaN  Abidjan      5    9  2020            84.6
105761  Africa  Ivory Coast    NaN  Abidjan      5   10  2020            84.4
105762  Africa  Ivory Coast    NaN  Abidjan      5   11  2020            78.3
105763  Africa  Ivory Coast    NaN  Abidjan      5   12  2020            82.1
105764  Africa  Ivory Coast    NaN  Abidjan      5   13  2020            81.3

[9266 rows x 8 columns]
Addis Ababa
       Region   Cou

In [42]:
group2 = dataframe8.groupby('Region')
print("Group2:\n ",group2)
print("Group2 Describe:\n ",group2.describe())


Group2:
Group2 Describe:
         State                                  Month            ...    Year  \
       count mean std min 25% 50% 75% max     count      mean  ...     75%   
Region                                                         ...           
Africa   0.0  NaN NaN NaN NaN NaN NaN NaN  251118.0  6.474757  ...  2013.0   
Asia     0.0  NaN NaN NaN NaN NaN NaN NaN  295401.0  6.470415  ...  2013.0   

               AvgTemperature                                                \
           max          count       mean        std   min   25%   50%   75%   
Region                                                                        
Africa  2020.0       251118.0  53.549517  57.068235 -99.0  63.4  75.0  80.7   
Asia    2020.0       295401.0  62.302704  36.421753 -99.0  55.0  75.0  82.6   

               
          max  
Region         
Africa  102.8  
Asia    103.7  

[2 rows x 40 columns]
Africa
        Region  Country  State     City  Month  Day  Year  AvgTemperature
0 

In [44]:

for region, region_df in group2:
    print(region)
    print(region_df)

Africa
        Region  Country  State     City  Month  Day  Year  AvgTemperature
0       Africa  Algeria    NaN  Algiers      1    1  1995            64.2
1       Africa  Algeria    NaN  Algiers      1    2  1995            49.4
2       Africa  Algeria    NaN  Algiers      1    3  1995            48.8
3       Africa  Algeria    NaN  Algiers      1    4  1995            46.4
4       Africa  Algeria    NaN  Algiers      1    5  1995            47.9
...        ...      ...    ...      ...    ...  ...   ...             ...
251113  Africa   Zambia    NaN   Lusaka      1   18  2014            71.3
251114  Africa   Zambia    NaN   Lusaka      1   19  2014            77.5
251115  Africa   Zambia    NaN   Lusaka      1   20  2014            73.4
251116  Africa   Zambia    NaN   Lusaka      1   21  2014            73.1
251117  Africa   Zambia    NaN   Lusaka      1   22  2014            71.3

[251118 rows x 8 columns]
Asia
       Region       Country  State     City  Month  Day  Year  AvgTempera

In [45]:
group1.get_group('Dhaka')

Region     Country  State   City  Month  Day  Year  AvgTemperature
251118   Asia  Bangladesh    NaN  Dhaka      1    1  1995            64.8
251119   Asia  Bangladesh    NaN  Dhaka      1    2  1995            58.4
251120   Asia  Bangladesh    NaN  Dhaka      1    3  1995           -99.0
251121   Asia  Bangladesh    NaN  Dhaka      1    4  1995            59.6
251122   Asia  Bangladesh    NaN  Dhaka      1    5  1995            64.9
...       ...         ...    ...    ...    ...  ...   ...             ...
256923   Asia  Bangladesh    NaN  Dhaka     11   22  2010           -99.0
256924   Asia  Bangladesh    NaN  Dhaka     11   23  2010           -99.0
256925   Asia  Bangladesh    NaN  Dhaka     11   24  2010           -99.0
256926   Asia  Bangladesh    NaN  Dhaka     11   25  2010           -99.0
256927   Asia  Bangladesh    NaN  Dhaka     11   26  2010            74.3

[5810 rows x 8 columns]

In [47]:
print(group1.get_group('Dhaka').describe)

<bound method NDFrame.describe of        Region     Country  State   City  Month  Day  Year  AvgTemperature
251118   Asia  Bangladesh    NaN  Dhaka      1    1  1995            64.8
251119   Asia  Bangladesh    NaN  Dhaka      1    2  1995            58.4
251120   Asia  Bangladesh    NaN  Dhaka      1    3  1995           -99.0
251121   Asia  Bangladesh    NaN  Dhaka      1    4  1995            59.6
251122   Asia  Bangladesh    NaN  Dhaka      1    5  1995            64.9
...       ...         ...    ...    ...    ...  ...   ...             ...
256923   Asia  Bangladesh    NaN  Dhaka     11   22  2010           -99.0
256924   Asia  Bangladesh    NaN  Dhaka     11   23  2010           -99.0
256925   Asia  Bangladesh    NaN  Dhaka     11   24  2010           -99.0
256926   Asia  Bangladesh    NaN  Dhaka     11   25  2010           -99.0
256927   Asia  Bangladesh    NaN  Dhaka     11   26  2010            74.3

[5810 rows x 8 columns]>


In [48]:
print(group1.get_group('Dhaka').describe())

       State        Month          Day         Year  AvgTemperature
count    0.0  5810.000000  5810.000000  5810.000000     5810.000000
mean     NaN     6.491566    15.721170  2002.455250       10.109880
std      NaN     3.434458     8.796922     4.586929       86.724555
min      NaN     1.000000     1.000000  1995.000000      -99.000000
25%      NaN     4.000000     8.000000  1998.000000      -99.000000
50%      NaN     7.000000    16.000000  2002.000000       70.500000
75%      NaN     9.000000    23.000000  2006.000000       82.600000
max      NaN    12.000000    31.000000  2010.000000       91.400000


In [65]:
print("Group1 \n",group1.describe())


Group1 
              State                                Month            ...  \
             count mean std min 25% 50% 75% max   count      mean  ...   
City                                                               ...   
Abidjan        0.0  NaN NaN NaN NaN NaN NaN NaN  9266.0  6.468919  ...   
Addis Ababa    0.0  NaN NaN NaN NaN NaN NaN NaN  9295.0  6.486928  ...   
Algiers        0.0  NaN NaN NaN NaN NaN NaN NaN  9266.0  6.468919  ...   
Almaty         0.0  NaN NaN NaN NaN NaN NaN NaN  9265.0  6.469077  ...   
Antananarivo   0.0  NaN NaN NaN NaN NaN NaN NaN  9266.0  6.468919  ...   
...            ...  ...  ..  ..  ..  ..  ..  ..     ...       ...  ...   
Tokyo          0.0  NaN NaN NaN NaN NaN NaN NaN  9266.0  6.468919  ...   
Tunis          0.0  NaN NaN NaN NaN NaN NaN NaN  9266.0  6.468919  ...   
Ulan-bator     0.0  NaN NaN NaN NaN NaN NaN NaN  9266.0  6.468919  ...   
Vientiane      0.0  NaN NaN NaN NaN NaN NaN NaN  9266.0  6.468919  ...   
Windhoek       0.0  NaN NaN N

In [70]:
print("Get group from Group : \n", group1.get_group('Dhaka'))
print("Describe Fucntion :\n",group1.get_group('Dhaka').describe())


Get group from Group : 
        Region     Country  State   City  Month  Day  Year  AvgTemperature
251118   Asia  Bangladesh    NaN  Dhaka      1    1  1995            64.8
251119   Asia  Bangladesh    NaN  Dhaka      1    2  1995            58.4
251120   Asia  Bangladesh    NaN  Dhaka      1    3  1995           -99.0
251121   Asia  Bangladesh    NaN  Dhaka      1    4  1995            59.6
251122   Asia  Bangladesh    NaN  Dhaka      1    5  1995            64.9
...       ...         ...    ...    ...    ...  ...   ...             ...
256923   Asia  Bangladesh    NaN  Dhaka     11   22  2010           -99.0
256924   Asia  Bangladesh    NaN  Dhaka     11   23  2010           -99.0
256925   Asia  Bangladesh    NaN  Dhaka     11   24  2010           -99.0
256926   Asia  Bangladesh    NaN  Dhaka     11   25  2010           -99.0
256927   Asia  Bangladesh    NaN  Dhaka     11   26  2010            74.3

[5810 rows x 8 columns]
Describe Fucntion :
        State        Month          Day   

In [76]:
group1.get_group('Dhaka')['Region'] # Fetch the value of Region from Grouping


251118    Asia
251119    Asia
251120    Asia
251121    Asia
251122    Asia
          ... 
256923    Asia
256924    Asia
256925    Asia
256926    Asia
256927    Asia
Name: Region, Length: 5810, dtype: object

In [77]:
group1.get_group('Dhaka')['Region'].describe() # Decribe fucntion


count     5810
unique       1
top       Asia
freq      5810
Name: Region, dtype: object

In [78]:

print("Max Average temprature of Region",group1['AvgTemperature'].max())

Max Average temprature of Region City
Abidjan         88.6
Addis Ababa     77.0
Algiers         96.6
Almaty          90.9
Antananarivo    78.5
                ... 
Tokyo           90.6
Tunis           96.4
Ulan-bator      87.5
Vientiane       97.0
Windhoek        92.2
Name: AvgTemperature, Length: 62, dtype: float64


In [79]:
df3 = group1.get_group('Abidjan') ## grt the frame by group by
for col in  df3.columns:
    print('\n ', col)
    print(df3[col].unique())


  Region
['Africa']

  Country
['Ivory Coast']

  State
[nan]

  City
['Abidjan']

  Month
[ 1  2  3  4  5  6  7  8  9 10 11 12]

  Day
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31]

  Year
[1995 1996 1997 1998 1999 2000 2001 2002 2003 2004 2005 2006 2007 2008
 2009 2010 2011 2012 2013 2014 2015 2016 2017 2018 2019 2020]

  AvgTemperature
[ 82.6  82.3  81.   83.3  83.4  84.1  82.5  81.3  79.7  80.9  77.5  73.8
  73.   74.9  76.7  78.9  80.1  80.3  79.   75.7  78.3  77.   82.4  79.8
  80.8  81.1  81.6  80.4  83.   82.7  82.2  82.9  81.8  81.9  83.1  83.6
  83.2  84.7  84.6  84.5  84.8  84.3  84.   84.2  83.9  82.8  81.4  83.7
  77.8  81.7  83.8  86.1  85.1  84.9  85.9  86.   86.7  76.9  83.5  79.5
  84.4  80.6  81.2  85.2  82.   79.1  79.2  79.6  78.7  79.9  81.5  82.1
  79.4  80.5  79.3  74.4  78.5  80.   80.2  77.9  78.8  78.4  78.1  77.1
  75.5  76.2  77.3  77.2  76.5  78.6  77.7  74.5  77.6  78.2  78.   76.8
  75.8 -99.   75.9  76.1

In [84]:
## Merging and Concate

india_Weather = pd.DataFrame({'City':['Mumbai','Delhi', 'Chandigarh'], 'Temperature': [32, 35,30], 'Humidity': [68,65,79]})
print("India Weather: \n",india_Weather)
us_Weather = pd.DataFrame({'City':['New york','Chicago', 'Orland'], 'Temperature': [21, 14,23], 'Humidity': [68,65,75]})
print("US Weather: \n",us_Weather)

print("Concatination with index:\n",pd.concat([india_Weather, us_Weather]))
print("Concatination without index:\n",pd.concat([india_Weather, us_Weather],ignore_index= True))

India Weather: 
          City  Temperature  Humidity
0      Mumbai           32        68
1       Delhi           35        65
2  Chandigarh           30        79
US Weather: 
        City  Temperature  Humidity
0  New york           21        68
1   Chicago           14        65
2    Orland           23        75
Concatination with index:
          City  Temperature  Humidity
0      Mumbai           32        68
1       Delhi           35        65
2  Chandigarh           30        79
0    New york           21        68
1     Chicago           14        65
2      Orland           23        75
Concatination without index:
          City  Temperature  Humidity
0      Mumbai           32        68
1       Delhi           35        65
2  Chandigarh           30        79
3    New york           21        68
4     Chicago           14        65
5      Orland           23        75


In [89]:
print("Concatination with axis is 1:\n",pd.concat([india_Weather, us_Weather],axis= 1))
print("Concatination with axis 0:\n",pd.concat([india_Weather, us_Weather],axis=0))

Concatination with axis is 1:
          City  Temperature  Humidity      City  Temperature  Humidity
0      Mumbai           32        68  New york           21        68
1       Delhi           35        65   Chicago           14        65
2  Chandigarh           30        79    Orland           23        75
Concatination with axis 0:
          City  Temperature  Humidity
0      Mumbai           32        68
1       Delhi           35        65
2  Chandigarh           30        79
0    New york           21        68
1     Chicago           14        65
2      Orland           23        75


In [90]:
print("Merging with inner:\n",pd.merge(india_Weather, us_Weather, on='Humidity',how='inner'))
# print("Concatination with outer\n",pd.concat([india_Weather, us_Weather],axis=0))

Merging with inner:
    City_x  Temperature_x  Humidity    City_y  Temperature_y
0  Mumbai             32        68  New york             21
1   Delhi             35        65   Chicago             14


In [91]:
print("Merging with inner:\n",pd.merge(india_Weather, us_Weather, on='Humidity',how='outer'))

Merging with inner:
        City_x  Temperature_x  Humidity    City_y  Temperature_y
0       Delhi           35.0        65   Chicago           14.0
1      Mumbai           32.0        68  New york           21.0
2         NaN            NaN        75    Orland           23.0
3  Chandigarh           30.0        79       NaN            NaN


In [92]:
print("Merging with inner:\n",pd.merge(india_Weather, us_Weather, on='Humidity',how='left'))

Merging with inner:
        City_x  Temperature_x  Humidity    City_y  Temperature_y
0      Mumbai             32        68  New york           21.0
1       Delhi             35        65   Chicago           14.0
2  Chandigarh             30        79       NaN            NaN


In [94]:
print("Merging with inner:\n",pd.merge(india_Weather, us_Weather, on='Humidity',how='right'))

Merging with inner:
    City_x  Temperature_x  Humidity    City_y  Temperature_y
0  Mumbai           32.0        68  New york             21
1   Delhi           35.0        65   Chicago             14
2     NaN            NaN        75    Orland             23


In [102]:
print("Merging with inner:\n",pd.merge(india_Weather, us_Weather,how='cross'))

Merging with inner:
        City_x  Temperature_x  Humidity_x    City_y  Temperature_y  Humidity_y
0      Mumbai             32          68  New york             21          68
1      Mumbai             32          68   Chicago             14          65
2      Mumbai             32          68    Orland             23          75
3       Delhi             35          65  New york             21          68
4       Delhi             35          65   Chicago             14          65
5       Delhi             35          65    Orland             23          75
6  Chandigarh             30          79  New york             21          68
7  Chandigarh             30          79   Chicago             14          65
8  Chandigarh             30          79    Orland             23          75


In [103]:
dataframe9 = pd.read_csv('city_temperature.csv', index_col='AvgTemperature')
print("DataFrame :\n",dataframe9)


DataFrame :
                 Region       Country  State     City  Month  Day  Year
AvgTemperature                                                        
64.2            Africa       Algeria    NaN  Algiers      1    1  1995
49.4            Africa       Algeria    NaN  Algiers      1    2  1995
48.8            Africa       Algeria    NaN  Algiers      1    3  1995
46.4            Africa       Algeria    NaN  Algiers      1    4  1995
47.9            Africa       Algeria    NaN  Algiers      1    5  1995
...                ...           ...    ...      ...    ...  ...   ...
49.2              Asia  Turkmenistan    NaN  Ashabad     11   18  2012
43.9              Asia  Turkmenistan    NaN  Ashabad     11   19  2012
40.7              Asia  Turkmenistan    NaN  Ashabad     11   20  2012
34.8              Asia  Turkmenistan    NaN  Ashabad     11   21  2012
35.9              Asia  Turkmenistan    NaN  Ashabad     11   22  2012

[546519 rows x 7 columns]


In [105]:
dataframe9.loc[48.8]

Region       Country  State     City  Month  Day  Year
AvgTemperature                                                        
48.8            Africa       Algeria    NaN  Algiers      1    3  1995
48.8            Africa       Algeria    NaN  Algiers      2    5  1995
48.8            Africa       Algeria    NaN  Algiers      2   24  1998
48.8            Africa       Algeria    NaN  Algiers      1   18  2000
48.8            Africa       Algeria    NaN  Algiers      2   25  2000
...                ...           ...    ...      ...    ...  ...   ...
48.8              Asia  Turkmenistan    NaN  Ashabad     11    9  2005
48.8              Asia  Turkmenistan    NaN  Ashabad      2   13  2006
48.8              Asia  Turkmenistan    NaN  Ashabad     11   11  2006
48.8              Asia  Turkmenistan    NaN  Ashabad      1   30  2007
48.8              Asia  Turkmenistan    NaN  Ashabad      2   20  2008

[241 rows x 7 columns]

In [106]:
dataframe9.iloc[2]

Region      Africa
Country    Algeria
State          NaN
City       Algiers
Month            1
Day              3
Year          1995
Name: 48.8, dtype: object