In [172]:
import numpy as np
import pandas as pd
import seaborn as sns

In [173]:
df = sns.load_dataset('iris')
df = df[df['species'] != 'virginica']
df

sepal_length  sepal_width  petal_length  petal_width     species
0            5.1          3.5           1.4          0.2      setosa
1            4.9          3.0           1.4          0.2      setosa
2            4.7          3.2           1.3          0.2      setosa
3            4.6          3.1           1.5          0.2      setosa
4            5.0          3.6           1.4          0.2      setosa
..           ...          ...           ...          ...         ...
95           5.7          3.0           4.2          1.2  versicolor
96           5.7          2.9           4.2          1.3  versicolor
97           6.2          2.9           4.3          1.3  versicolor
98           5.1          2.5           3.0          1.1  versicolor
99           5.7          2.8           4.1          1.3  versicolor

[100 rows x 5 columns]

In [174]:
df['species'].unique()

array(['setosa', 'versicolor'], dtype=object)

In [175]:
df['species'] = df['species'].map({'setosa':0,'versicolor':1})

In [176]:
df['species'].unique()

array([0, 1], dtype=int64)

In [177]:
X = df.iloc[::-1]
y = df.iloc[:,-1]
df.iloc()

In [178]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size=0.2, random_state=42)

In [179]:
X_train

sepal_length  sepal_width  petal_length  petal_width  species
44           5.1          3.8           1.9          0.4        0
11           4.8          3.4           1.6          0.2        0
73           6.1          2.8           4.7          1.2        1
57           4.9          2.4           3.3          1.0        1
30           4.8          3.1           1.6          0.2        0
..           ...          ...           ...          ...      ...
39           5.1          3.4           1.5          0.2        0
28           5.2          3.4           1.4          0.2        0
85           6.0          3.4           4.5          1.6        1
7            5.0          3.4           1.5          0.2        0
48           5.3          3.7           1.5          0.2        0

[80 rows x 5 columns]

In [180]:
y_train

55    1
88    1
26    0
42    0
69    1
     ..
60    1
71    1
14    0
92    1
51    1
Name: species, Length: 80, dtype: int64

In [181]:
from sklearn.linear_model import LogisticRegression
model = LogisticRegression()

In [182]:
model.fit(X_train,y_train)

LogisticRegression()

In [183]:
predicted = model.predict(X_test)

In [184]:
from sklearn.metrics import accuracy_score, precision_recall_curve, f1_score,confusion_matrix, precision_score

In [185]:
confusion_matrix(y_test,predicted)

array([[12,  0],
       [ 0,  8]], dtype=int64)

In [186]:
accuracy_score(y_test,predicted)

1.0

In [187]:
precision_score(y_test,predicted)

1.0

In [188]:
f1_score(y_test, predicted)

1.0

In [189]:
print(precision_recall_curve(y_test,predicted))

(array([0.4, 1. , 1. ]), array([1., 1., 0.]), array([0, 1], dtype=int64))


In [190]:
from sklearn.metrics import classification_report ## Provide full report 


In [191]:
print(classification_report(y_test,predicted))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        12
           1       1.00      1.00      1.00         8

    accuracy                           1.00        20
   macro avg       1.00      1.00      1.00        20
weighted avg       1.00      1.00      1.00        20



## Logistic Regression with Regularization  https://archive.ics.uci.edu/dataset/45/heart+disease


In [192]:
df = pd.read_csv('processed.cleveland.data')
df
columns = ["age","sex", "cp","trestbos","chol","fbs", "restecg","thalach","exand","oldpeach", "slop", "cs","thal","target"]
data = pd.read_csv('processed.cleveland.data', names=columns, header= None, na_values= "?")
data = data.reset_index(drop = True)
data

age  sex   cp  trestbos   chol  fbs  restecg  thalach  exand  oldpeach  \
0    63.0  1.0  1.0     145.0  233.0  1.0      2.0    150.0    0.0       2.3   
1    67.0  1.0  4.0     160.0  286.0  0.0      2.0    108.0    1.0       1.5   
2    67.0  1.0  4.0     120.0  229.0  0.0      2.0    129.0    1.0       2.6   
3    37.0  1.0  3.0     130.0  250.0  0.0      0.0    187.0    0.0       3.5   
4    41.0  0.0  2.0     130.0  204.0  0.0      2.0    172.0    0.0       1.4   
..    ...  ...  ...       ...    ...  ...      ...      ...    ...       ...   
298  45.0  1.0  1.0     110.0  264.0  0.0      0.0    132.0    0.0       1.2   
299  68.0  1.0  4.0     144.0  193.0  1.0      0.0    141.0    0.0       3.4   
300  57.0  1.0  4.0     130.0  131.0  0.0      0.0    115.0    1.0       1.2   
301  57.0  0.0  2.0     130.0  236.0  0.0      2.0    174.0    0.0       0.0   
302  38.0  1.0  3.0     138.0  175.0  0.0      0.0    173.0    0.0       0.0   

     slop   cs  thal  target  
0     3.0  0.0   6.0       0  
1     2.0  3.0   3.0       2  
2     2.0  2.0   7.0       1  
3     3.0  0.0   3.0       0  
4     1.0  0.0   3.0       0  
..    ...  ...   ...     ...  
298   2.0  0.0   7.0       1  
299   2.0  2.0   7.0       2  
300   2.0  1.0   7.0       3  
301   2.0  1.0   3.0       1  
302   1.0  NaN   3.0       0  

[303 rows x 14 columns]

In [193]:
data = data.dropna()
data

age  sex   cp  trestbos   chol  fbs  restecg  thalach  exand  oldpeach  \
0    63.0  1.0  1.0     145.0  233.0  1.0      2.0    150.0    0.0       2.3   
1    67.0  1.0  4.0     160.0  286.0  0.0      2.0    108.0    1.0       1.5   
2    67.0  1.0  4.0     120.0  229.0  0.0      2.0    129.0    1.0       2.6   
3    37.0  1.0  3.0     130.0  250.0  0.0      0.0    187.0    0.0       3.5   
4    41.0  0.0  2.0     130.0  204.0  0.0      2.0    172.0    0.0       1.4   
..    ...  ...  ...       ...    ...  ...      ...      ...    ...       ...   
297  57.0  0.0  4.0     140.0  241.0  0.0      0.0    123.0    1.0       0.2   
298  45.0  1.0  1.0     110.0  264.0  0.0      0.0    132.0    0.0       1.2   
299  68.0  1.0  4.0     144.0  193.0  1.0      0.0    141.0    0.0       3.4   
300  57.0  1.0  4.0     130.0  131.0  0.0      0.0    115.0    1.0       1.2   
301  57.0  0.0  2.0     130.0  236.0  0.0      2.0    174.0    0.0       0.0   

     slop   cs  thal  target  
0     3.0  0.0   6.0       0  
1     2.0  3.0   3.0       2  
2     2.0  2.0   7.0       1  
3     3.0  0.0   3.0       0  
4     1.0  0.0   3.0       0  
..    ...  ...   ...     ...  
297   2.0  0.0   7.0       1  
298   2.0  0.0   7.0       1  
299   2.0  2.0   7.0       2  
300   2.0  1.0   7.0       3  
301   2.0  1.0   3.0       1  

[297 rows x 14 columns]

In [194]:
# convert into binary classification
data['target']= (data['target'] > 0).astype(int)
data

C:\Users\parde\AppData\Local\Temp\ipykernel_25908\1305901866.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['target']= (data['target'] > 0).astype(int)


age  sex   cp  trestbos   chol  fbs  restecg  thalach  exand  oldpeach  \
0    63.0  1.0  1.0     145.0  233.0  1.0      2.0    150.0    0.0       2.3   
1    67.0  1.0  4.0     160.0  286.0  0.0      2.0    108.0    1.0       1.5   
2    67.0  1.0  4.0     120.0  229.0  0.0      2.0    129.0    1.0       2.6   
3    37.0  1.0  3.0     130.0  250.0  0.0      0.0    187.0    0.0       3.5   
4    41.0  0.0  2.0     130.0  204.0  0.0      2.0    172.0    0.0       1.4   
..    ...  ...  ...       ...    ...  ...      ...      ...    ...       ...   
297  57.0  0.0  4.0     140.0  241.0  0.0      0.0    123.0    1.0       0.2   
298  45.0  1.0  1.0     110.0  264.0  0.0      0.0    132.0    0.0       1.2   
299  68.0  1.0  4.0     144.0  193.0  1.0      0.0    141.0    0.0       3.4   
300  57.0  1.0  4.0     130.0  131.0  0.0      0.0    115.0    1.0       1.2   
301  57.0  0.0  2.0     130.0  236.0  0.0      2.0    174.0    0.0       0.0   

     slop   cs  thal  target  
0     3.0  0.0   6.0       0  
1     2.0  3.0   3.0       1  
2     2.0  2.0   7.0       1  
3     3.0  0.0   3.0       0  
4     1.0  0.0   3.0       0  
..    ...  ...   ...     ...  
297   2.0  0.0   7.0       1  
298   2.0  0.0   7.0       1  
299   2.0  2.0   7.0       1  
300   2.0  1.0   7.0       1  
301   2.0  1.0   3.0       1  

[297 rows x 14 columns]

In [195]:
X = data.drop('target', axis = 1)
y = data['target']
X_no_header = pd.DataFrame(X.values)
Y_no_header = pd.Series(y.values)
print(X_no_header)


       0    1    2      3      4    5    6      7    8    9    10   11   12
0    63.0  1.0  1.0  145.0  233.0  1.0  2.0  150.0  0.0  2.3  3.0  0.0  6.0
1    67.0  1.0  4.0  160.0  286.0  0.0  2.0  108.0  1.0  1.5  2.0  3.0  3.0
2    67.0  1.0  4.0  120.0  229.0  0.0  2.0  129.0  1.0  2.6  2.0  2.0  7.0
3    37.0  1.0  3.0  130.0  250.0  0.0  0.0  187.0  0.0  3.5  3.0  0.0  3.0
4    41.0  0.0  2.0  130.0  204.0  0.0  2.0  172.0  0.0  1.4  1.0  0.0  3.0
..    ...  ...  ...    ...    ...  ...  ...    ...  ...  ...  ...  ...  ...
292  57.0  0.0  4.0  140.0  241.0  0.0  0.0  123.0  1.0  0.2  2.0  0.0  7.0
293  45.0  1.0  1.0  110.0  264.0  0.0  0.0  132.0  0.0  1.2  2.0  0.0  7.0
294  68.0  1.0  4.0  144.0  193.0  1.0  0.0  141.0  0.0  3.4  2.0  2.0  7.0
295  57.0  1.0  4.0  130.0  131.0  0.0  0.0  115.0  1.0  1.2  2.0  1.0  7.0
296  57.0  0.0  2.0  130.0  236.0  0.0  2.0  174.0  0.0  0.0  2.0  1.0  3.0

[297 rows x 13 columns]


In [196]:
## Normalise Features
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X_no_header)
X_scaled

array([[ 0.93618065,  0.69109474, -2.24062879, ...,  2.26414539,
        -0.72197605,  0.65587737],
       [ 1.3789285 ,  0.69109474,  0.87388018, ...,  0.6437811 ,
         2.47842525, -0.89422007],
       [ 1.3789285 ,  0.69109474,  0.87388018, ...,  0.6437811 ,
         1.41162482,  1.17257652],
       ...,
       [ 1.48961547,  0.69109474,  0.87388018, ...,  0.6437811 ,
         1.41162482,  1.17257652],
       [ 0.27205887,  0.69109474,  0.87388018, ...,  0.6437811 ,
         0.34482438,  1.17257652],
       [ 0.27205887, -1.44697961, -1.20245913, ...,  0.6437811 ,
         0.34482438, -0.89422007]])

In [207]:
#Train Test Split
X_train, X_test,y_train, y_test = train_test_split(X_scaled, y, test_size=0.2, random_state= 42)
X_train
y_test

169    0
214    1
63     0
155    1
5      0
77     0
185    0
159    0
9      1
140    0
290    1
78     0
93     0
102    0
42     0
225    0
288    0
33     0
267    1
149    0
248    1
45     1
60     1
46     0
282    1
240    0
177    1
237    1
17     0
283    0
112    0
222    0
24     1
82     0
7      0
75     0
109    1
84     0
91     1
73     1
117    0
127    1
236    1
59     0
198    0
211    1
98     0
187    1
178    0
125    0
94     0
299    1
184    1
279    0
195    1
297    1
25     0
227    0
6      1
183    0
Name: target, dtype: int32

In [198]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
model = LogisticRegression()
model.fit(X_train, y_train)
y_pred = model.predict(X_test)

In [199]:
accuracy = accuracy_score (y_test, y_pred)
confusion_matrix = confusion_matrix(y_test, y_pred)
report = classification_report(y_test, y_pred)

In [200]:
print(accuracy)

0.8666666666666667


In [201]:
print(report)

              precision    recall  f1-score   support

           0       0.89      0.89      0.89        36
           1       0.83      0.83      0.83        24

    accuracy                           0.87        60
   macro avg       0.86      0.86      0.86        60
weighted avg       0.87      0.87      0.87        60



In [202]:
print(confusion_matrix)

[[32  4]
 [ 4 20]]


#Logistic Regression with L1 and L2 Regularizer

In [203]:
# L1 Regularlizer - (Lasso)
model_l1 = LogisticRegression(penalty ='l1', solver = 'liblinear', C = 1.0) ## Liblinear id use for identify and ignore the less important feature


In [208]:
model_l1.fit(X_train, y_train)
predict_l1_y_test = model_l1.predict(X_test)
predict_l1_y_test
print(y_test.shape)
print(predict_l1_y_test.shape)

(60,)
(60,)


In [210]:
#Evaluation
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
confusion_matrix_l1 = confusion_matrix(predict_l1_y_test, y_test)
print(confusion_matrix_l1)
accuracy_l1 = accuracy_score(predict_l1_y_test,y_test)
print(accuracy_l1)

[[32  2]
 [ 4 22]]
0.9


In [ ]:
# L2 Regularlizer - (Ridge)
model_l2 = LogisticRegression(penalty ='l2', solver = 'liblinear', C = 1.0) ## Liblinear id use for identify and ignore the less important feature
model_l2.fit(X_train, y_train)
predict_l2_y_test = model_l2.predict(X_test)
predict_l2_y_test
print(y_test.shape)
print(predict_l2_y_test.shape)

#Evaluation
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
confusion_matrix_l2 = confusion_matrix(predict_l2_y_test, y_test)
print(confusion_matrix_l2)
accuracy_l2 = accuracy_score(predict_l2_y_test,y_test)
print(accuracy_l2)

(60,)
(60,)
[[32  4]
 [ 4 20]]
0.8666666666666667


In [223]:
## Elastic
model_elastic = LogisticRegression(penalty= 'elasticnet', solver = 'saga', C = 1.0, l1_ratio=0.5) ## saga is use for identify and ignore the less important feature
model_elastic.fit(X_train, y_train)
predict_elastic_y_test =model_elastic.predict(X_test)
predict_elastic_y_test
print(y_test.shape)
print(predict_l2_y_test.shape)

#Evaluation
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
confusion_matrix_elastic = confusion_matrix(predict_elastic_y_test, y_test)
print(confusion_matrix_elastic)
report_elastic = classification_report(predict_elastic_y_test,y_test)
print(report_elastic)
accuracy_elastic = accuracy_score(predict_elastic_y_test,y_test)
print(accuracy_elastic)

(60,)
(60,)
[[32  3]
 [ 4 21]]
              precision    recall  f1-score   support

           0       0.89      0.91      0.90        35
           1       0.88      0.84      0.86        25

    accuracy                           0.88        60
   macro avg       0.88      0.88      0.88        60
weighted avg       0.88      0.88      0.88        60

0.8833333333333333
