In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import pickle
from ydata_profiling import ProfileReport
from sklearn.linear_model import LinearRegression


In [2]:
dataset = pd.read_csv('Advertising.csv')
dataset.describe()

Unnamed: 0          TV       Radio   Newspaper       Sales
count  200.000000  200.000000  200.000000  200.000000  200.000000
mean   100.500000  147.042500   23.264000   30.554000   14.022500
std     57.879185   85.854236   14.846809   21.778621    5.217457
min      1.000000    0.700000    0.000000    0.300000    1.600000
25%     50.750000   74.375000    9.975000   12.750000   10.375000
50%    100.500000  149.750000   22.900000   25.750000   12.900000
75%    150.250000  218.825000   36.525000   45.100000   17.400000
max    200.000000  296.400000   49.600000  114.000000   27.000000

In [3]:
dataset.head()

Unnamed: 0     TV  Radio  Newspaper  Sales
0           1  230.1   37.8       69.2   22.1
1           2   44.5   39.3       45.1   10.4
2           3   17.2   45.9       69.3    9.3
3           4  151.5   41.3       58.5   18.5
4           5  180.8   10.8       58.4   12.9

In [4]:
pf = ProfileReport(dataset) ## ProfileReport function is cover the EDA part in one function
pf.to_widgets()

Summarize dataset:   0%|          | 0/5 [00:00<?, ?it/s]

Generate report structure:   0%|          | 0/1 [00:00<?, ?it/s]

Render widgets:   0%|          | 0/1 [00:00<?, ?it/s]

In [32]:
pf.to_file('Advertising.html')

Export report to file:   0%|          | 0/1 [00:00<?, ?it/s]

In [33]:
x= dataset[["TV"]]
x

TV
0    230.1
1     44.5
2     17.2
3    151.5
4    180.8
..     ...
195   38.2
196   94.2
197  177.0
198  283.6
199  232.1

[200 rows x 1 columns]

In [34]:
y = dataset[["Sales"]]
y

Sales
0     22.1
1     10.4
2      9.3
3     18.5
4     12.9
..     ...
195    7.6
196    9.7
197   12.8
198   25.5
199   13.4

[200 rows x 1 columns]

In [35]:
# sklearn  model used  in Machine Learning for Linear Regression
from sklearn.linear_model import LinearRegression
linear_model = LinearRegression()

In [36]:
#Data set is small so not using Train Test model
linear_model.fit(x,y)


LinearRegression()

In [43]:
linear_model.intercept_    ### In line equation y = mx+c the value of c is interceptor or constant

array([7.03259355])

In [44]:
linear_model.coef_     ## In line equation y =mx+c, the value of m is coeffecient or slope

array([[0.04753664]])

In [45]:
import pickle ## to Save the Model using pickle
file = "linear_reg.sav"  # to save the regression  model file
pickle.dump(linear_model, open(file,"wb"))  

In [46]:
# to check the investment  45 in TV impact on Sales
linear_model.predict([[45]]) ## Calculation of y prediction.

c:\Users\parde\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([[9.17174237]])

In [47]:
list = [5,7,9,12,45,67,89,100]
for i in list:
    print(linear_model.predict([[i]]))

[[7.27027675]]
[[7.36535003]]
[[7.46042331]]
[[7.60303323]]
[[9.17174237]]
[[10.21754846]]
[[11.26335455]]
[[11.78625759]]


c:\Users\parde\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
c:\Users\parde\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
c:\Users\parde\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
c:\Users\parde\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
c:\Users\parde\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but Line

In [49]:
## To calculate R2 for accuracy of cost function -
linear_model.score(x,y)  ## Accuracy of cost function  or Error Rate or Best Fit line is 61.18%

0.611875050850071

In [50]:
# now calculate score based on Newpapaer

x = dataset[["Newspaper"]]
y =  dataset[["Sales"]]

In [51]:
# sklearn  model used  in Machine Learning
from sklearn.linear_model import LinearRegression
linear_modelN = LinearRegression()
#Data set is small so not using Train Test model
linear_modelN.fit(x,y)
print('Interceptor or value of c in line y = ',linear_modelN.intercept_)
print('Coeffiecient or value of m in best fit line ',linear_modelN.coef_)
fileN = "linear_regN.sav"  # to save the regression  model file
pickle.dump(linear_modelN, open(fileN,"wb"))  
## To calculate R2
print('the value of R2 for accuracy',linear_modelN.score(x,y))

Interceptor or value of c in line y =  [12.35140707]
Coeffiecient or value of m in best fit line  [[0.0546931]]
the value of R2 for accuracy 0.05212044544430516


In [52]:
# now calculate score based on Radio

x = dataset[["Radio"]]
y =  dataset[["Sales"]]
# sklearn  model used  in Machine Learning
from sklearn.linear_model import LinearRegression
linear_modelR = LinearRegression()
#Data set is small so not using Train Test model
linear_modelR.fit(x,y)
print('Interceptor or value of c in line y = ',linear_modelR.intercept_)
print('Coeffiecient or value of m in best fit line ',linear_modelR.coef_)
fileR = "linear_regR.sav"  # to save the regression model file for radio
pickle.dump(linear_modelR, open(fileR,"wb"))  
## To calculate R2
## To calculate R2
print('the value of R2 for accuracy',linear_modelR.score(x,y))

Interceptor or value of c in line y =  [9.3116381]
Coeffiecient or value of m in best fit line  [[0.20249578]]
the value of R2 for accuracy 0.33203245544529525


In [53]:
## To show the saved model 

saved_model = pickle.load(open(file,'rb'))
saved_model.predict([[5]])

c:\Users\parde\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([[7.27027675]])

In [54]:
saved_model = pickle.load(open(fileR,'rb'))
saved_model.predict([[5]])

c:\Users\parde\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([[10.32411701]])

In [55]:
saved_model = pickle.load(open(fileN,'rb'))
saved_model.predict([[5]])

c:\Users\parde\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([[12.62487256]])

In [56]:
data_x = dataset[['TV','Radio','Newspaper']]
data_y = dataset['Sales']
linear_modelFull = LinearRegression()
#Data set is small so not using Train Test model
print(linear_modelFull.fit(data_x,data_y))
print(linear_modelFull.intercept_) ## Intercepteptor is Q0 value
print(linear_modelFull.coef_)  ## its the angel or slop
print(linear_modelFull.predict([[15,15,15]]))
print(linear_modelFull.score(data_x,data_y))


LinearRegression()
2.938889369459412
[ 0.04576465  0.18853002 -0.00103749]
[6.43774691]
0.8972106381789522


c:\Users\parde\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


In [57]:
# After removing the Newspaper the from feature then the impact is negligible
data_x = dataset[['TV','Radio']]
data_y = dataset['Sales']
linear_modelFull = LinearRegression()
#Data set is small so not using Train Test model
print(linear_modelFull.fit(data_x,data_y))
print(linear_modelFull.intercept_)
print(linear_modelFull.coef_)
print(linear_modelFull.predict([[15,15]]))
print(linear_modelFull.score(data_x,data_y))

LinearRegression()
2.9210999124051362
[0.04575482 0.18799423]
[6.42733554]
0.8971942610828957


c:\Users\parde\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


In [59]:
### We can also use the state model in place of linear model
import statsmodels.formula.api as smf
lm = smf.ols(formula='Sales ~ TV', data=dataset).fit()   ## ols means oridinary least square
lm.summary() ## Check the probablity value


<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:                  Sales   R-squared:                       0.612
Model:                            OLS   Adj. R-squared:                  0.610
Method:                 Least Squares   F-statistic:                     312.1
Date:                Mon, 26 Aug 2024   Prob (F-statistic):           1.47e-42
Time:                        20:18:40   Log-Likelihood:                -519.05
No. Observations:                 200   AIC:                             1042.
Df Residuals:                     198   BIC:                             1049.
Df Model:                           1                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
Intercept      7.0326      0.458     15.360      0.000       6.130       7.935
TV             0.0475      0.003     17.668      0.000       0.042       0.053
==============================================================================
Omnibus:                        0.531   Durbin-Watson:                   1.935
Prob(Omnibus):                  0.767   Jarque-Bera (JB):                0.669
Skew:                          -0.089   Prob(JB):                        0.716
Kurtosis:                       2.779   Cond. No.                         338.
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""

In [60]:
### We can also use the state model in place of liner model
import statsmodels.formula.api as smf
lm = smf.ols(formula='Sales ~ TV+Radio', data=dataset).fit()   ## ols means oridinary least square of TV and Radio
lm.summary()

# here probability value id 0 whih means its 100 % impacted the Sales price

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:                  Sales   R-squared:                       0.897
Model:                            OLS   Adj. R-squared:                  0.896
Method:                 Least Squares   F-statistic:                     859.6
Date:                Mon, 26 Aug 2024   Prob (F-statistic):           4.83e-98
Time:                        20:18:51   Log-Likelihood:                -386.20
No. Observations:                 200   AIC:                             778.4
Df Residuals:                     197   BIC:                             788.3
Df Model:                           2                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
Intercept      2.9211      0.294      9.919      0.000       2.340       3.502
TV             0.0458      0.001     32.909      0.000       0.043       0.048
Radio          0.1880      0.008     23.382      0.000       0.172       0.204
==============================================================================
Omnibus:                       60.022   Durbin-Watson:                   2.081
Prob(Omnibus):                  0.000   Jarque-Bera (JB):              148.679
Skew:                          -1.323   Prob(JB):                     5.19e-33
Kurtosis:                       6.292   Cond. No.                         425.
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""

In [61]:
### We can also use the state model in place of liner model
import statsmodels.formula.api as smf
lm = smf.ols(formula='Sales ~ TV+Radio+Newspaper', data=dataset).fit()   ## ols means oridinary least square of TV, Newspaper and Radio
lm.summary()

# here probability value  of newspaper is not 0 whih means its not impacted the Sales price we can exclude it

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:                  Sales   R-squared:                       0.897
Model:                            OLS   Adj. R-squared:                  0.896
Method:                 Least Squares   F-statistic:                     570.3
Date:                Mon, 26 Aug 2024   Prob (F-statistic):           1.58e-96
Time:                        20:19:04   Log-Likelihood:                -386.18
No. Observations:                 200   AIC:                             780.4
Df Residuals:                     196   BIC:                             793.6
Df Model:                           3                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
Intercept      2.9389      0.312      9.422      0.000       2.324       3.554
TV             0.0458      0.001     32.809      0.000       0.043       0.049
Radio          0.1885      0.009     21.893      0.000       0.172       0.206
Newspaper     -0.0010      0.006     -0.177      0.860      -0.013       0.011
==============================================================================
Omnibus:                       60.414   Durbin-Watson:                   2.084
Prob(Omnibus):                  0.000   Jarque-Bera (JB):              151.241
Skew:                          -1.327   Prob(JB):                     1.44e-33
Kurtosis:                       6.332   Cond. No.                         454.
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""